"""CLI tool installers for the shared runtime.

Importing this package is side-effect free: it does not download archives,
install tools, start processes, or probe authentication. Call
:func:`ensure_goose` / :func:`ensure_muse` only from explicit provider
resolution paths.
"""

from __future__ import annotations

from .goose import (
    DEFAULT_MANIFEST_NAME,
    GOOSE_EXECUTABLE,
    GOOSE_EXECUTABLE_WINDOWS,
    LINUX_VARIANTS,
    WINDOWS_VARIANTS,
    GooseInstallResult,
    GooseReadiness,
    assess_goose_readiness,
    default_manifest_path,
    detect_linux_libc,
    detect_platform,
    discover_goose,
    ensure_goose,
    goose_auth_available,
    goose_auto_install_enabled,
    install_goose_from_manifest,
    load_release_manifest,
    managed_executable_path,
    managed_install_root,
    normalize_arch,
    normalize_os,
    select_release_asset,
    validate_platform,
)
from .catalog import (
    CLI_INSTALLERS,
    CliInstallerSpec,
    CliToolInstallResult,
    discover_cli_tool,
    ensure_cli_tool,
    installer_robustness_report,
)
from .muse import (
    MUSE_EXECUTABLE,
    OFFICIAL_INSTALL_URL,
    MuseInstallResult,
    MuseReadiness,
    assess_muse_readiness,
    default_install_dir,
    default_launcher_path,
    discover_muse,
    ensure_muse,
    muse_auth_available,
    muse_auto_install_enabled,
)

__all__ = [
    "DEFAULT_MANIFEST_NAME",
    "GOOSE_EXECUTABLE",
    "GOOSE_EXECUTABLE_WINDOWS",
    "LINUX_VARIANTS",
    "WINDOWS_VARIANTS",
    "GooseInstallResult",
    "GooseReadiness",
    "assess_goose_readiness",
    "default_manifest_path",
    "detect_linux_libc",
    "detect_platform",
    "discover_goose",
    "ensure_goose",
    "goose_auth_available",
    "goose_auto_install_enabled",
    "install_goose_from_manifest",
    "load_release_manifest",
    "managed_executable_path",
    "managed_install_root",
    "normalize_arch",
    "normalize_os",
    "select_release_asset",
    "validate_platform",
    "MUSE_EXECUTABLE",
    "OFFICIAL_INSTALL_URL",
    "MuseInstallResult",
    "MuseReadiness",
    "assess_muse_readiness",
    "default_install_dir",
    "default_launcher_path",
    "discover_muse",
    "ensure_muse",
    "muse_auth_available",
    "muse_auto_install_enabled",
    "CLI_INSTALLERS",
    "CliInstallerSpec",
    "CliToolInstallResult",
    "discover_cli_tool",
    "ensure_cli_tool",
    "installer_robustness_report",
]
