"""Repository handoff and overlay contract family (EAAEF-020)."""

from .contracts import (
    REPOSITORY_HANDOFF_CONTRACT_FAMILY,
    REPOSITORY_HANDOFF_CONTRACT_VERSION,
    AttributeAndModeRecord,
    FileKind,
    HookPolicy,
    LfsPointerRecord,
    NestedRepoRecord,
    OriginAndShallowBounds,
    RefusalReason,
    RepositoryHandoffBounds,
    RepositoryHandoffContractError,
    RepositoryHandoffMode,
    RepositoryHandoffRefusal,
    RepositoryHandoffRefusalError,
    RepositoryHandoffRequest,
    RepositoryOverlay,
    SparseCheckoutRecord,
    SubmoduleRecord,
    decode_repository_handoff_contract,
)

__all__ = (
    "REPOSITORY_HANDOFF_CONTRACT_FAMILY",
    "REPOSITORY_HANDOFF_CONTRACT_VERSION",
    "AttributeAndModeRecord",
    "FileKind",
    "HookPolicy",
    "LfsPointerRecord",
    "NestedRepoRecord",
    "OriginAndShallowBounds",
    "RefusalReason",
    "RepositoryHandoffBounds",
    "RepositoryHandoffContractError",
    "RepositoryHandoffMode",
    "RepositoryHandoffRefusal",
    "RepositoryHandoffRefusalError",
    "RepositoryHandoffRequest",
    "RepositoryOverlay",
    "SparseCheckoutRecord",
    "SubmoduleRecord",
    "decode_repository_handoff_contract",
)
