name: GitHub Actions Template (Updated March 2025)

# This is an up-to-date template for GitHub Actions workflows
# with the correct action versions to avoid CI/CD failures

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        required: true
        default: 'standard'
        type: choice
        options:
          - standard
          - hardware-only
          - web-only
          - all

jobs:
  example-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    # IMPORTANT: Use v4 for the checkout action
    - name: Checkout code
      uses: actions/checkout@v4
      
    # IMPORTANT: Use v4 for the setup-python action
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    
    - name: Run tests
      run: |
        pytest -xvs tests/
    
    # IMPORTANT: Use v4 for the upload-artifact action
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results/
        retention-days: 14
        
  example-web-job:
    runs-on: ubuntu-latest
    needs: example-job
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # IMPORTANT: Use v4 for the setup-python action
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Run web tests
      run: |
        echo "Running web tests"
    
    # IMPORTANT: Use v4 for the upload-artifact action
    - name: Upload web test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: web-test-results
        path: web-test-results/
        
    # IMPORTANT: Use v4 for the peaceiris/actions-gh-pages action if deploying to GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        destination_dir: docs