# Auto-Healing Configuration for GitHub Actions
# This file configures the automatic workflow failure healing system

# Enable/disable auto-healing globally
enabled: true

# Workflows to monitor (use '*' for all workflows)
monitored_workflows:
  - "*"  # Monitor all workflows by default
  
# Workflows to exclude from auto-healing
excluded_workflows:
  - "Auto-Heal Workflow Failures"  # Don't heal the healer
  - "Weekly Documentation Maintenance"  # Documentation workflows typically don't need auto-heal

# Maximum number of auto-heal attempts per workflow per day
max_heal_attempts_per_day: 3

# Require manual approval before creating PR
require_manual_approval: false

# Auto-merge fixes if tests pass
auto_merge_on_success: false

# Labels to apply to auto-heal issues and PRs
labels:
  issues:
    - "auto-heal"
    - "workflow-failure"
    - "automated"
  pull_requests:
    - "auto-heal"
    - "automated-fix"
    - "needs-review"

# Notification settings
notifications:
  # Create issue for every failure
  create_issue: true
  
  # Mention specific users for certain workflow failures
  mentions:
    "AMD64 CI/CD Pipeline": []
    "ARM64 CI/CD Pipeline": []
    default: []  # No mentions by default

# Copilot settings
copilot:
  # Use GitHub Copilot Workspace for auto-healing
  enabled: true
  
  # Copilot model preferences
  model: "gpt-4"
  
  # Temperature for code generation (0.0-1.0, lower = more conservative)
  temperature: 0.2
  
  # Include context files for better analysis
  include_context:
    - "README.md"
    - "requirements.txt"
    - "pyproject.toml"
    - ".github/workflows/*.yml"

# Failure analysis settings
analysis:
  # Number of log lines to include in analysis
  max_log_lines: 200
  
  # Keywords to identify in failure logs
  error_keywords:
    - "error"
    - "failed"
    - "exception"
    - "traceback"
    - "fatal"
    - "panic"
    - "exit code"
    - "timeout"
    - "killed"
  
  # Common failure patterns and suggested fixes
  failure_patterns:
    - pattern: "no space left on device"
      suggestion: "Add disk cleanup step or increase runner disk space"
    
    - pattern: "timeout"
      suggestion: "Increase timeout value or optimize long-running operations"
    
    - pattern: "permission denied"
      suggestion: "Check file permissions or add sudo where needed"
    
    - pattern: "module not found"
      suggestion: "Add missing dependency to requirements or install step"
    
    - pattern: "connection refused"
      suggestion: "Check service availability or add service health check"
    
    - pattern: "docker.*build.*failed"
      suggestion: "Review Dockerfile and build context"

# Branch naming for auto-heal attempts
branch_naming:
  prefix: "auto-heal"
  include_workflow_id: true
  include_timestamp: true

# PR settings
pull_request:
  # Template for PR title
  title_template: "🤖 Auto-Heal: Fix {workflow_name} Failure (Run #{run_id})"
  
  # Template for PR description
  description_template: |
    ## 🔧 Automated Workflow Fix
    
    This PR was automatically generated by the Auto-Heal system to fix a workflow failure.
    
    ### Failure Details
    
    - **Workflow**: {workflow_name}
    - **Run ID**: {run_id}
    - **Branch**: {branch}
    - **Failed Jobs**: {failed_jobs_count}
    - **Tracking Issue**: #{issue_number}
    
    ### Changes Made
    
    {changes_description}
    
    ### Testing
    
    - [ ] All tests pass
    - [ ] No new errors introduced
    - [ ] Original workflow issue is fixed
    
    ### Review Checklist
    
    - [ ] Review the changes for correctness
    - [ ] Verify the fix addresses the root cause
    - [ ] Check for any side effects
    - [ ] Ensure coding standards are maintained
    
    ---
    *This PR was created by GitHub Copilot Auto-Healing system*
    *Review carefully before merging*
  
  # Draft mode (create as draft PR)
  draft: true
  
  # Request reviews from
  reviewers: []
  
  # Request reviews from teams
  team_reviewers: []

# Retry settings
retry:
  # Retry the original workflow after fix is merged
  retry_on_merge: true
  
  # Wait time before retrying (in minutes)
  retry_delay: 5

# Logging and reporting
logging:
  # Keep artifacts for analysis
  retention_days: 30
  
  # Include full logs in artifacts
  include_full_logs: true
  
  # Generate detailed reports
  generate_reports: true

# Security settings
security:
  # Only allow auto-heal from trusted branches
  trusted_branches:
    - "main"
    - "develop"
    - "master"
  
  # Require code review before merging auto-heal PRs
  require_code_review: true
  
  # Run security scans on auto-heal changes
  run_security_scans: true
  
  # Maximum file changes allowed in auto-heal PR
  max_file_changes: 20
