from setuptools import setup, find_packages
from pathlib import Path

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
	name='ipfs_accelerate_py',
	version='0.0.45',
	packages=find_packages(),
	description="A comprehensive framework for hardware-accelerated machine learning inference with IPFS network-based distribution",
	long_description=long_description,
	long_description_content_type="text/markdown",
	author="Benjamin Barber",
	author_email="starworks5@gmail.com",
	url="https://github.com/endomorphosis/ipfs_accelerate_py",
	classifiers=[
		"Programming Language :: Python :: 3",
		"License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
		"Operating System :: POSIX :: Linux", 
	],
	python_requires=">=3.8",
	keywords="machine learning, IPFS, hardware-acceleration, inference, distributed computing, WebGPU, WebNN",
	install_requires=[
		'ipfs_kit_py',
		'sentence_transformers',
		'transformers>=4.46',
		'ipfs_transformers_py',
		'ipfs_model_manager_py',
		'torch>=2.1',
		'torchvision',
		'numpy',
		'torchtext',
		'urllib3',
		'requests',
		'boto3',
		'trio',
		'InstructorEmbedding',
		'FlagEmbedding',
		'llama-cpp-python',
		'gguf',
		'optimum',
		'optimum[openvino]',
		'optimum[exporters]',
		'optimum[intel]',
		'toml',
		'pydantic',
		'einops',
		'timm',
		'Pillow',
		'multiformats',
		'pydub',
		'openai',
		'tiktoken',
		'open_clip_torch',
		'librosa',
		'pysbd',
		'ffmpeg-python',
		'opencv-python',
		'decord',
		'websocket-client',
		'google-generativeai',
		'anthropic',
		'duckdb>=0.10.0',
		'pandas>=2.2.0',
		'fastapi>=0.110.0',
		'uvicorn>=0.27.0',
		'websockets>=12.0.0',
		'jinja2>=3.1.0',
		'plotly>=5.22.0',
		'seaborn>=0.13.0',
		'pytest>=8.0.0',
		'python-dotenv>=1.0.0',
		'pyarrow>=14.0.0',
		'psutil>=5.9.0',
		'selenium>=4.10.0',
		'scikit-learn>=1.0.0',
		'statsmodels>=0.14.0',
		'matplotlib>=3.7.0'
	]
)