from pathlib import Path
import hashlib,json,shutil
W=Path('/home/barberb/lift_coding');B=Path(__file__).resolve().parent;A=W/'.worktrees/ir-release-accelerate-20261002';D=W/'.worktrees/ir-release-datasets-20261002';P=B/'public-evidence';assert not P.exists();P.mkdir()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def raw(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode()
def write(name,v):
 p=P/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
def copy(src,name):
 p=P/name;p.parent.mkdir(parents=True,exist_ok=True);assert src.stat().st_size<=2*1024**2;shutil.copyfile(src,p)
def read(name):return json.loads((B/name).read_text())
q=read('qualification-01/qualification.json');c=q['source384'];ex=read('qualification-exit.json');assert q['qualified'] and c['qualified'] and ex['returncode']==0 and ex['cleanup_verified'] and ex['source_pins_unchanged'] and ex['public_task_inputs_unchanged']
manifest=read('bundle/manifest.json');audit=read('build-audit.json');frozen=read('frozen-production-pins.json');rows={r['path']:r for r in manifest['files']}
assert len(rows)==26922 and len(audit['changed'])==6 and len(audit['added'])==4 and not audit['removed']
assert sha(B/'bundle/manifest.json')==audit['manifest_sha256']
for name,pin in frozen.items():
 prefix,rel=name.split('/',1);src={'source':A,'datasets':D}[prefix]/rel
 assert sha(src)==rows[name]['sha256']==pin
# Framework snapshots only, no task sources, databases, models, or private state.
for name in audit['changed']+audit['added']:
 prefix,rel=name.split('/',1);src={'source':A,'datasets':D}[prefix]/rel;copy(src,'runtime-sources/'+name)
for name in ('build_fresh.py','run_qualification.py','build_public_evidence.py','build-controller-exit.json','build-exit.json','build-command.json','final-build-command.json','build-audit.json','frozen-production-pins.json','independent-build-audit.json','run-admission.json','qualification-command.json','qualification-controller-start.json','qualification-controller-exit.json','qualification-controller.stdout','qualification-controller.stderr','qualification-exit.json','qualification-before-pins.json','qualification-after-pins.json','qualification-public-task-pins.json','qualification-containers-before.json','qualification-containers-after.json','resources-before.json','admission-schema-check.json','run-admission.template.json','qualification-command.template.json'):
 copy(B/name,'receipts/'+name)
for name in ('resources.json','admission-estimate.json','final-resources/resources.json','final-resources/admission-estimate.json','source384-probe-status.json','source384-probe.stderr','setup-cache/setup-cache-advice.json'):
 copy(B/'qualification-01'/name,'receipts/native/'+name)
write('archive-binding.json',dict(archive_sha256=manifest['archive_sha256'],archive_bytes=(B/'bundle/runtime.tar.gz').stat().st_size,manifest_sha256=sha(B/'bundle/manifest.json'),members=len(rows),source_revisions=audit['source_revisions'],changed=audit['changed'],added=audit['added'],removed=[],framework_rows=[rows[n] for n in sorted(frozen)],source384=manifest['source384'],torch_cpu_wheel=manifest['torch_cpu_wheel'],setup_cache_policy=q['setup_cache']['policy'],full_archive_body_audit='build-audit.json; no second archive read for this package'))
inference=B/'qualification-01/native-inference.json';v=json.loads(inference.read_bytes());report=v['report'];artifact=raw(report)
assert sha(inference)==c['inference_sha256'] and v['artifact']==dict(bytes=len(artifact),sha256=hashlib.sha256(artifact).hexdigest())
assert report['key']==c['native_inference_key'] and report['coverage']==c['coverage'] and report['worker_receipt']==c['native_worker_receipt']
assert v['native_worker_executed'] and v['inference_executed'] and report['output']['model_loads']==1
assert report['key']['embedding_cache_policy']=='verified_snapshot_dontneed_best_effort@1'
write('inference-binding.json',dict(export_sha256=sha(inference),export_bytes=inference.stat().st_size,export_payload_included=False,immutable_report_artifact=v['artifact'],canonical_report_verified=True,native_inference_key_sha256=hashlib.sha256(raw(report['key'])).hexdigest(),producer=c['producer'],numerical_producer=report['key']['producer'],checkpoint_sha256=c['checkpoint_sha256'],config_sha256=c['config_sha256'],embedding_assets=report['key']['embedding_assets'],embedding_cache_policy=report['key']['embedding_cache_policy'],source_head=c['source_head'],signed_source_hashes=c['signed_source_hashes'],coverage=c['coverage'],model_loads=1,inference_executed=True,native_worker_executed=True,worker_receipt={k:x for k,x in report['worker_receipt'].items() if k not in ('parent_lease_id','child_lease_id')},neural_inference_replayed=False,source_qualified_proof_claimed=False))
summary={k:x for k,x in c['source384_summary'].items() if k not in ('candidate_samples','excluded_source_files')};summary['published_candidate_sample_count']=len(c['source384_summary']['candidate_samples']);write('planning-summary.json',summary)
write('qualification-summary.json',dict(schema='ordinary-source384-lifetime-advice-qualification@1',qualified=True,archive_sha256=manifest['archive_sha256'],profile=q['resource_profile'],original_container_sources_consumed=q['original_container_sources_consumed'],setup=dict(qualified=q['deployment']['qualified'],seconds=q['deployment']['seconds'],steps=q['deployment']['steps'],task_source_preserved=q['deployment']['task_source_preserved'],policy=q['setup_cache']['policy'],advice_completed=q['setup_cache']['completed']),timings={k:c[k] for k in ('seconds','prepare_seconds','initial_context_seconds','context_seconds','source384_seconds','warm_observation_seconds','context_nonoverlapping_seconds')},source384_native_deadline_seconds=90,qualification_inner_seconds=270,qualification_exec_seconds=300,qualification_outer_seconds=2300,controller_seconds=read('qualification-controller-exit.json')['seconds'],coverage=c['coverage'],resources_before=q['resources_before'],resources_after=q['resources_after'],cleanup_verified=True,source_pins_unchanged=True,public_task_inputs_unchanged=True,provider_calls=0,training_steps=0,download_calls_during_inference=0,benchmark_result=False,official_verifier_executed=False,proof_authority=False,freed_memory_measured=False))
old=W/'artifacts/source384-production-cache-20261003';oldq=json.loads((old/'qualification-01/qualification.json').read_text());oldv=json.loads((old/'verdict.json').read_text())
write('comparison.json',dict(schema='ordinary-qualification-comparison@1',previous=dict(archive_sha256=oldq['deployment']['archive_sha256'],evidence_manifest_sha256=sha(old/'public-evidence/manifest.json'),qualified=False,failure='LeaseTimeoutError at second cold-replay observation',context_seconds=oldv['initial_context_seconds'],resources_before=oldq['resources_before'],post_unwind_failure_resources=oldv['post_unwind_failure_resources']),current=dict(archive_sha256=manifest['archive_sha256'],qualified=True,source384_seconds=c['source384_seconds'],initial_context_seconds=c['initial_context_seconds'],warm_observation_seconds=c['warm_observation_seconds'],resources_before=q['resources_before'],resources_after=q['resources_after']),interpretation='Two single runs under uncontrolled host conditions and multiple source changes; no causal allocation/speedup/freed-byte attribution. Previous failed phase timing is not a matched completed phase. Current success qualifies this retained runtime only, not full supervisor benchmark reward.',changed_framework_paths=audit['changed'],added_framework_paths=audit['added']))
(P/'README.md').write_text('''# Ordinary Source384 qualification after verified-asset advice

The fresh original-task Docker qualification passed with the unchanged five-CPU,12GiB profile. Source384 preparation/inference completed in76.883949 seconds against its90-second deadline. Initial-context reconstruction and replay completed in137.808814 seconds; the full native probe took159.484326 seconds and the controller423.839956 seconds including setup. A separate warm observation took10.264095 seconds. Cleanup and all public-task/runtime source pins passed.

Actual checkpoint inference used one model load and a13.272-second bounded CPU worker. The exported inference body and immutable canonical report digest were verified; source bodies and model payloads are deliberately excluded here. The220 signed inputs yielded31 Python files and944 functions:128 were selected,127 decoded as unverified candidates, and one was deferred by the GTE token limit. Every decoded candidate remained `fail_open_source_contract_unsupported`. The planning summary exposes two samples and omits125; it confers no proof, completion or execution authority.

Setup retained the exact finite archive/native-binary/library advice policies. Source384's requested `verified_snapshot_dontneed_best_effort@1` policy is bound to the inference key and verifier producer hash. The full asset byte reads and subsequent advice are not measurements of cache residency or freed memory. Before/after available memory was9339/8968MiB; those samples do not isolate any component's memory effect.

The archive differs from the retained preceding archive in exactly six changed and four added framework files. The scoped GTE verifier change, caller object lifetime change and failure diagnostics are included; three newly added code modules and one changed training module are inactive in this runtime. The previous ordinary run failed at a second cold-replay child admission. This comparison comprises two uncontrolled single runs with multiple changes, not a causal speedup, memory benchmark or repeatability claim.

Component admission retained D47 passing controls under its then-existing16CPU/99688MiB ledger, A18 caller tests, A11/13 checkpoint cases with two foreign-lease admission refusals, and39 diagnostics controls. No blocked host case was relabeled passed. The current container's own ordinary native qualification succeeded.

No provider, training, official verifier or full benchmark ran through this qualifier. The root-owned subsequent full trial is separate and is not included in this closed package. This package includes framework source snapshots and source-free receipts only: no task source/instruction bodies, weights, CAS/database contents, credential contents or scheduler capabilities. Public source hashes remain as provenance. The original full runtime archive,manifest and inference export are referenced by hash and retained outside the package.
''')
files=[dict(path=str(p.relative_to(P)),bytes=p.stat().st_size,sha256=sha(p)) for p in sorted(P.rglob('*')) if p.is_file()]
write('manifest.json',dict(schema='ordinary-source384-lifetime-advice-evidence@1',files=files))
print(json.dumps(dict(path=str(P),manifest_sha256=sha(P/'manifest.json'),members=len(files),bytes=sum(r['bytes'] for r in files)),indent=2))
