import hashlib,json,pathlib,subprocess,xml.etree.ElementTree as ET
B=pathlib.Path(__file__).parent
A=pathlib.Path('/home/barberb/lift_coding/.worktrees/ir-release-accelerate-20261002')
def read(name):return json.loads((B/name).read_text())
archive=read('bundle/manifest.json');pins=read('prepared-a-pins.json')+read('frozen-d-pins.json');by={x['path']:x for x in archive['files']}
for p in pins:
 assert by[p['path']]['sha256']==p['sha256']
 assert hashlib.sha256((B/'frozen-sources'/p['path']).read_bytes()).hexdigest()==p['sha256']
assert hashlib.sha256((B/'bundle/runtime.tar.gz').read_bytes()).hexdigest()==archive['archive_sha256']
d=read('docker-01/deployment/deployment.json');c=read('docker-01/source384-context.json');r=read('docker-01/resources.json')
assert d['original_inputs']==d['retained_inputs'] and len(d['original_inputs']['files'])==218
assert read('docker-01/source384-result.json')==c
assert read('docker-01/source384-probe-status.json')['return_code']==1
assert c['error'].startswith('bounded source-unit worker failed: timeout:') and c['qualified'] is False
selection=read('consumer-test-selection.json');prefix=selection['prefix'];root=ET.parse(B.parent/'terminal-source384-context-20261003'/(prefix+'.xml')).getroot();assert len(list(root.iter('testcase')))==13 and not any(list(root.iter(x)) for x in ('failure','error','skipped'))
container='ipfs-native-deploy-1791015700-main-1';check=subprocess.run(['docker','ps','-a','--filter','name='+container,'--format','{{.Names}} {{.Status}}'],capture_output=True,text=True,check=True);assert not check.stdout.strip()
(B/'cleanup-observation.json').write_text(json.dumps(dict(command=check.args,returncode=check.returncode,stdout=check.stdout,stderr=check.stderr,container_absent=True),indent=2)+'\n')
summary=dict(schema='source384-docker-reconstruction-qualification@1',qualified=False,archive_sha256=archive['archive_sha256'],resource_profile='source384-5cpu-12gib@1',deployment_qualified=d['qualified'],empty_native_start_passed=any(x['step']=='empty-native-start' and x['return_code']==0 for x in d['steps']),original_source_files=218,original_source_hashes_preserved=True,bottle_sha256=d['original_inputs']['files']['bottle.py']['sha256'],resources_before=r,failure_resources=c['failure_resources'],timings_seconds=dict(deployment=d['seconds'],prepare=c['prepare_seconds'],initial_context=c['phase_seconds'],probe=c['seconds'],total=read('exit.json')['seconds']),error_type=c['error_type'],error_summary='bounded source-unit worker failed: timeout',failure_phase=c['error_phase'],failure_call_site='infer_shared_parent_units _worker after first observe_current and context assembly returned',publication_returned=True,first_observation_returned=True,bounded_worker_invoked=True,child_import_output_observed=True,successful_model_load_qualified=False,completed_neural_inference_qualified=False,native_inference_artifact_exported=False,native_context_budget_seconds=90,deadlines_weakened=False,report_collection_qualified=True,probe_return_code=1,container_absent=True,provider_calls=0,training_steps=0,model_download_calls=0,official_verifier_executed=False,benchmark_result=False,source_qualified_proof_claimed=False,current_producer_consumer_tests=dict(passed=13,failed=0,skipped=0,pytest_seconds=selection['pytest_seconds'],scope='Separate real-checkpoint component tests; not successful Docker inference.'),producer_pins=pins,previous_closed_manifest_sha256='12e074d7166a944ca9e819e5c8ea022344f2e364b1b8cb7ada1ecb8fd7e9e920',limits=['No successful model-load or inference receipt; bounded worker invocation and child import output are evidenced.','Native context budget remains90 seconds; initial context elapsed98.298s including surrounding work and bounded cleanup.','Resource samples and aggregate phase timing do not isolate publication/observation/worker costs or prove a cause.','Slow pinned dependency installation is separate from native context timing.','Optional live Docker registry inspection was skipped to avoid measurement overlap.','No official benchmark score, token comparison, or source-qualified proof.'])
(B/'qualification-summary.json').write_text(json.dumps(summary,sort_keys=True,indent=2)+'\n')
print(json.dumps({'archive_and_pins_verified':len(pins),'inputs':218,'consumer_tests':13,'container_absent':True,'qualified':False}))
