from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default_lm import hf_lm
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default_lm import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default_embed import hf_embed
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default_embed import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_xclip import hf_xclip
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_xclip import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_llama import hf_llama
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_llama import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_bert import hf_bert
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_bert import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_llava import hf_llava
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_llava import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default import default
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.default import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_clap import hf_clap
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_clap import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_clip import hf_clip
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_clip import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_wav2vec2 import hf_wav2vec2
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_wav2vec2 import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_t5 import hf_t5
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_t5 import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.chat_format import chat_format
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.chat_format import *
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_whisper import hf_whisper
from test.tests.other.ipfs_accelerate_py_tests.worker.skillset.hf_whisper import *
from test.tests.other.ipfs_accelerate_py_tests.worker.openvino_utils import *
from test.tests.other.ipfs_accelerate_py_tests.worker.worker import worker_py
from test.tests.other.ipfs_accelerate_py_tests.worker.worker import *