"""Explicit simulation namespace. Results here are never live."""

from __future__ import annotations

from .fabricated_hardware import (
    CUDA_MOCK_NAMESPACE,
    MOCK_HARDWARE_NAMESPACE,
    FabricatedHardwareError,
    MockHardwareDetection,
    UnavailableHardwareDetection,
    UnavailableTorch,
    create_simulated_cuda_implementation,
    instantiate_mock_hardware_detection,
    load_ordinary_hardware_detection,
    torch_is_fabricated,
)
from .legacy_mock_coordinator import (
    LEGACY_MOCK_COORDINATOR_NAMESPACE,
    LegacyMockCoordinatorError,
    MockWorker,
    UnavailableWorker,
    admit_legacy_workflow_coordinator,
    instantiate_mock_worker,
    load_ordinary_runtime_worker,
    quarantined_coordinator_unavailable_result,
)
from .pseudo_cid import (
    MOCK_IPFS_NAMESPACE,
    PSEUDO_CID_NAMESPACE,
    MockIPFSClient,
    PseudoCidIdentityError,
    UnavailableIpfsClient,
    instantiate_mock_ipfs_client,
    load_ordinary_ipfs_client,
    load_ordinary_multiformats,
    mint_canonical_cid,
    ordinary_store_to_ipfs,
    random_cid,
    simulate_store_to_ipfs,
)

__all__ = (
    "CUDA_MOCK_NAMESPACE",
    "LEGACY_MOCK_COORDINATOR_NAMESPACE",
    "MOCK_HARDWARE_NAMESPACE",
    "MOCK_IPFS_NAMESPACE",
    "PSEUDO_CID_NAMESPACE",
    "FabricatedHardwareError",
    "LegacyMockCoordinatorError",
    "MockHardwareDetection",
    "MockIPFSClient",
    "MockWorker",
    "PseudoCidIdentityError",
    "UnavailableHardwareDetection",
    "UnavailableIpfsClient",
    "UnavailableTorch",
    "UnavailableWorker",
    "admit_legacy_workflow_coordinator",
    "create_simulated_cuda_implementation",
    "instantiate_mock_hardware_detection",
    "instantiate_mock_ipfs_client",
    "instantiate_mock_worker",
    "load_ordinary_hardware_detection",
    "load_ordinary_ipfs_client",
    "load_ordinary_multiformats",
    "load_ordinary_runtime_worker",
    "mint_canonical_cid",
    "ordinary_store_to_ipfs",
    "quarantined_coordinator_unavailable_result",
    "random_cid",
    "simulate_store_to_ipfs",
    "torch_is_fabricated",
)
