name: 'Cleanup Workspace'
description: 'Clean runner workspace and fix permissions before checkout'
branding:
  icon: 'trash-2'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Remove stale git locks
      shell: bash
      run: |
        echo "ðŸ”’ Removing stale git lock files..."
        find "${GITHUB_WORKSPACE}" -name "*.lock" -type f -delete 2>/dev/null || true
        find "${GITHUB_WORKSPACE}" -name "index.lock" -type f -delete 2>/dev/null || true
        echo "âœ… Lock files removed"
      continue-on-error: true
    
    - name: Fix git directory permissions
      shell: bash
      run: |
        echo "ðŸ“ Fixing .git directory permissions and ownership..."
        if [ -d "${GITHUB_WORKSPACE}/.git" ]; then
          # Fix ownership if files are owned by root (common in containerized workflows)
          current_user=$(whoami)
          if sudo -n test -f "${GITHUB_WORKSPACE}/.git/index" 2>/dev/null; then
            owner=$(stat -c '%U' "${GITHUB_WORKSPACE}/.git/index" 2>/dev/null || echo "$current_user")
            if [ "$owner" != "$current_user" ]; then
              echo "  Fixing ownership from $owner to $current_user..."
              sudo -n chown -R "$current_user:$current_user" "${GITHUB_WORKSPACE}/.git" 2>/dev/null || true
            fi
          fi
          # Fix directory permissions
          find "${GITHUB_WORKSPACE}/.git" -type d -exec chmod u+rwx {} \; 2>/dev/null || true
          # Fix file permissions
          find "${GITHUB_WORKSPACE}/.git" -type f -exec chmod u+rw {} \; 2>/dev/null || true
          # Fix git logs specifically (common permission issue in Actions)
          if [ -d "${GITHUB_WORKSPACE}/.git/logs" ]; then
            chmod u+rwx "${GITHUB_WORKSPACE}/.git/logs" 2>/dev/null || true
            find "${GITHUB_WORKSPACE}/.git/logs" -type d -exec chmod u+rwx {} \; 2>/dev/null || true
            find "${GITHUB_WORKSPACE}/.git/logs" -type f -exec chmod u+rw {} \; 2>/dev/null || true
          fi
          echo "âœ… .git permissions fixed"
        else
          echo "â„¹ï¸ No .git directory found"
        fi
      continue-on-error: true
    
    - name: Fix .github directory permissions
      shell: bash
      run: |
        echo "ðŸ“ Fixing .github directory permissions..."
        if [ -d "${GITHUB_WORKSPACE}/.github" ]; then
          find "${GITHUB_WORKSPACE}/.github" -type d -exec chmod u+rwx {} \; 2>/dev/null || true
          find "${GITHUB_WORKSPACE}/.github" -type f -exec chmod u+rw {} \; 2>/dev/null || true
          echo "âœ… .github permissions fixed"
        else
          echo "â„¹ï¸ No .github directory found"
        fi
      continue-on-error: true
    
    - name: Clean Python cache
      shell: bash
      run: |
        echo "ðŸ Cleaning Python cache files..."
        find "${GITHUB_WORKSPACE}" -name "*.pyc" -delete 2>/dev/null || true
        find "${GITHUB_WORKSPACE}" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
        echo "âœ… Python cache cleaned"
      continue-on-error: true
    
    - name: Report disk usage
      shell: bash
      run: |
        echo "ðŸ“Š Disk usage:"
        df -h "${RUNNER_WORKSPACE}" 2>/dev/null || df -h "${GITHUB_WORKSPACE}" 2>/dev/null || true
      continue-on-error: true
