"""Autonomous agent supervisor helpers for objective-driven todo execution."""

from .dataset_store import DatasetArtifact, ObjectiveDatasetStore
from .objective_graph import (
    BundleWriteResult,
    ObjectiveFinding,
    ObjectiveGoal,
    ObjectiveHeapRecord,
    ObjectiveTaskRecord,
    assign_goal_subgoal_packets,
    collect_ast_dataset_records,
    build_bundle_task_payloads,
    generate_objective_todos,
    goal_graph,
    objective_heap_schedule,
    persist_objective_ast_dataset,
    parse_goal_heap,
    plan_semantic_ast_bundles,
    scan_objective_gaps,
    submit_bundle_tasks,
    write_bundle_shards,
)
from .objective_tracker import (
    ObjectiveCompletionResult,
    ObjectiveTrackingResult,
    RepositoryComponent,
    append_interoperability_goals,
    append_refinement_goals,
    build_objective_thought_graph,
    discover_gitlink_paths,
    discover_gitmodule_paths,
    discover_repository_components,
    discover_submodule_paths,
    ensure_objective_tracking_document,
    fibonacci_priority,
    reconcile_objective_goal_completion,
    run_goal_validation,
    write_objective_graph_artifact,
)
from .todo_vector_index import (
    TodoIndexRecord,
    build_execution_packet,
    build_execution_packets,
    cluster_records,
    parse_todo_vector_records,
    write_todo_vector_index,
)

__all__ = [
    "BundleWriteResult",
    "BundleLaneSpec",
    "ActionContractCodegenConfig",
    "ActionContractSyncTarget",
    "AndroidValidationCallbacks",
    "AgentSupervisorRuntimeBootstrapCallbacks",
    "BootstrapPathCallbacks",
    "BootstrapPathSpec",
    "CodebaseScanEnvSettings",
    "CodebaseFinding",
    "ConfiguredBacklogRecorderBundle",
    "ConfiguredCodebaseScanRecorder",
    "ConfiguredActionContractSyncRunner",
    "ConfiguredDaemonBootstrapRunner",
    "ConfiguredImplementationDaemonRunner",
    "ConfiguredMergeResolverRunner",
    "ConfiguredMultiSupervisorLauncher",
    "ConfiguredMultiSupervisorCliRunner",
    "ConfiguredObjectiveBacklogRecorder",
    "ConfiguredRetryBudgetRecorder",
    "ConfiguredSupervisorBootstrapRunner",
    "ConfiguredSupervisorEntrypoint",
    "ConfiguredSupervisorRuntime",
    "ConfiguredTaskProposalRouterRunner",
    "DatasetArtifact",
    "DEFAULT_REPO_DOCS_DIR",
    "DEFAULT_CODEBASE_SCAN_DATA_SUBDIRS",
    "AGENT_SUPERVISOR_DIRECTORY_BOOTSTRAP_KEYS",
    "AgentSupervisorNamespacePaths",
    "ObjectiveFinding",
    "ObjectiveGoal",
    "ObjectiveHeapRecord",
    "ObjectiveDatasetStore",
    "ObjectiveCompletionResult",
    "ObjectiveTrackingResult",
    "ObjectiveTaskRecord",
    "ObjectiveRefillEnvSettings",
    "RepositoryComponent",
    "append_interoperability_goals",
    "append_refinement_goals",
    "android_validation_command_needs_environment",
    "android_validation_environment_contract",
    "agent_supervisor_bootstrap_path_entries",
    "agent_supervisor_namespace_paths",
    "apply_env_defaults",
    "apply_environment_contract",
    "assign_goal_subgoal_packets",
    "build_bundle_task_payloads",
    "build_configured_backlog_recorder_bundle",
    "build_configured_action_contract_sync_runner",
    "build_execution_packet",
    "build_execution_packets",
    "build_action_contract_sync_arg_parser",
    "build_action_contract_sync_targets",
    "build_merge_prompt",
    "build_configured_merge_resolver_arg_parser",
    "build_configured_merge_resolver_runner",
    "build_namespace_merge_resolver_runner",
    "build_configured_daemon_bootstrap_runner",
    "build_configured_implementation_daemon_runner",
    "build_namespace_daemon_bootstrap_runner",
    "build_namespace_configured_implementation_daemon_runner",
    "build_configured_multi_supervisor_launcher",
    "build_configured_multi_supervisor_cli_runner",
    "build_repo_implementation_multi_supervisor_launcher",
    "build_configured_implementation_supervisor_entrypoint",
    "build_configured_supervisor_bootstrap_runner",
    "build_configured_supervisor_runtime",
    "build_script_supervisor_bootstrap_runner",
    "build_script_supervisor_runtime",
    "build_configured_task_proposal_router_runner",
    "build_llm_merge_resolver_invoker",
    "build_merge_prompt_callback",
    "build_namespace_codebase_scan_recorder",
    "build_objective_daemon_arg_parser",
    "build_namespace_objective_backlog_recorder",
    "build_namespace_retry_budget_recorder",
    "build_objective_thought_graph",
    "build_resolver_payload_callback",
    "build_bootstrap_path_ensurer",
    "build_bootstrap_path_resolver",
    "build_agent_supervisor_bootstrap_path_callbacks",
    "build_agent_supervisor_runtime_bootstrap_callbacks",
    "build_prefixed_bootstrap_path_callbacks",
    "build_android_validation_callbacks",
    "build_default_llm_merge_resolver_command_callback",
    "build_prefixed_default_llm_merge_resolver_command_callback",
    "build_repo_runtime_environment_callbacks",
    "build_runtime_environment_callback",
    "build_runtime_environment_callbacks",
    "collect_ast_dataset_records",
    "cluster_records",
    "generate_objective_todos",
    "ensure_objective_tracking_document",
    "discover_gitlink_paths",
    "discover_gitmodule_paths",
    "discover_repository_components",
    "discover_submodule_paths",
    "csv_tuple",
    "default_llm_merge_resolver_command",
    "data_namespace_scan_skip_prefixes",
    "env_csv_tuple",
    "env_int",
    "env_path",
    "env_str",
    "environment_assignment_prefix",
    "ensure_named_directories",
    "ensure_task_blocks_present",
    "enforce_android_validation_environment",
    "ensure_runtime_pythonpath",
    "fibonacci_priority",
    "goal_graph",
    "objective_heap_schedule",
    "launch_bundle_lanes",
    "invoke_llm_resolver",
    "JavaScriptActionContractConfig",
    "latest_failed_merge_event",
    "load_action_definitions_from_descriptor",
    "operation_action_mapper",
    "parse_goal_heap",
    "parse_todo_vector_records",
    "plan_semantic_ast_bundles",
    "plan_bundle_lanes",
    "prefixed_bootstrap_path_spec",
    "prefixed_bootstrap_path_specs",
    "prefixed_codebase_scan_env_settings",
    "prefixed_env_csv_tuple",
    "prefixed_env_int",
    "prefixed_env_path",
    "prefixed_env_str",
    "prefixed_env_var",
    "prefixed_interoperability_focus",
    "prefixed_objective_refill_env_settings",
    "PythonActionContractConfig",
    "persist_objective_ast_dataset",
    "record_configured_codebase_scan_findings",
    "record_configured_objective_backlog_findings",
    "record_configured_retry_budget_findings",
    "record_codebase_scan_findings",
    "record_objective_backlog_findings",
    "record_retry_budget_findings",
    "reconcile_objective_goal_completion",
    "repo_external_package_root",
    "repo_external_package_roots",
    "repo_doc_path",
    "repo_root_from_env",
    "repo_relative_or_default",
    "repo_script_command",
    "repo_script_path",
    "repo_task_board_path",
    "render_js_action_contract",
    "render_python_action_contract",
    "resolve_and_ensure_bootstrap_paths",
    "resolve_bootstrap_paths",
    "resolve_append_only_markdown_conflicts",
    "resolver_payload",
    "run_backlog_refinery",
    "run_action_contract_sync",
    "run_goal_validation",
    "run_bundle_supervisor",
    "run_objective_daemon",
    "scan_codebase_findings",
    "scan_objective_gaps",
    "submit_bundle_tasks",
    "sync_contract_targets",
    "task_board_env_var",
    "task_board_filename",
    "task_board_path_key",
    "task_board_path_option",
    "write_objective_graph_artifact",
    "write_bundle_shards",
    "write_bundle_lane_manifest",
    "write_todo_vector_index",
    "unique_path_entries",
    "with_android_validation_environment",
    "with_default",
    "with_exclusive_flag_default",
    "with_flag_default",
    "with_repeated_default",
    "TodoIndexRecord",
    "merge_append_only_markdown_sections",
    "common_supervisor_args_from_parsed_args",
    "implementation_supervisor_compact_track_spec",
    "implementation_supervisor_compact_track_specs",
    "implementation_supervisor_common_args",
    "implementation_supervisor_namespace_track_config",
    "implementation_supervisor_track_spec",
    "parse_implementation_supervisor_track_spec",
    "parse_supervisor_track_spec",
    "run_supervisor_tracks",
    "SupervisorTrack",
    "build_task_proposal_prompt",
    "build_task_proposal_prompt_builder",
    "build_task_proposal_router_cli_config",
    "build_repo_task_proposal_router_runner",
    "build_repo_task_proposal_route_runner",
    "build_task_blocks_ensurer",
    "build_codebase_refill_defaults_from_paths",
    "build_namespace_codebase_refill_defaults_factory",
    "build_namespace_objective_refill_defaults_factory",
    "build_portal_implementation_daemon_from_args",
    "build_portal_implementation_supervisor_from_args",
    "build_daemon_refill_hooks",
    "build_daemon_refill_hooks_factory_from_recorders",
    "build_daemon_refill_hooks_from_recorders",
    "build_daemon_codebase_scan_refill_callback",
    "build_implementation_daemon_defaults_from_paths",
    "build_implementation_supervisor_defaults_from_paths",
    "build_objective_refill_defaults_factory",
    "build_objective_refill_defaults_from_paths",
    "build_daemon_objective_refill_callback",
    "build_daemon_retry_budget_refill_callback",
    "build_codebase_refill_defaults_factory",
    "build_supervisor_refill_hooks",
    "build_supervisor_refill_hooks_factory_from_recorders",
    "build_supervisor_refill_hooks_from_recorders",
    "build_supervisor_codebase_scan_refill_callback",
    "build_supervisor_objective_refill_callback",
    "build_supervisor_retry_budget_refill_callback",
    "build_supervisor_runtime_callbacks",
    "build_supervisor_runtime_operations",
    "bootstrap_runtime_environment",
    "configure_daemon_logging",
    "configure_supervisor_logging",
    "apply_merge_resolver_environment",
    "apply_portal_implementation_daemon_defaults",
    "apply_portal_implementation_daemon_defaults_from_paths",
    "apply_portal_implementation_supervisor_defaults",
    "apply_portal_implementation_supervisor_defaults_from_paths",
    "implementation_state_artifact_paths",
    "namespace_implementation_state_artifact_paths",
    "implementation_state_paths",
    "implementation_supervisor_args",
    "run_portal_implementation_daemon_loop",
    "run_portal_implementation_supervisor",
    "run_configured_portal_implementation_daemon",
    "run_configured_portal_implementation_supervisor",
    "run_configured_portal_implementation_supervisor_with_runtime",
    "run_configured_merge_resolver_cli",
    "run_configured_task_proposal_router_cli",
    "run_task_proposal_router",
    "run_task_proposal_router_cli",
    "rewrite_validation_commands",
    "select_proposal_task",
    "standard_task_proposal_requested_outputs",
    "DaemonLoopHook",
    "ImplementationDaemonRunContext",
    "ImplementationDaemonDefaults",
    "ImplementationSupervisorTrackConfig",
    "ImplementationSupervisorRunContext",
    "ImplementationSupervisorDefaults",
    "MergeResolverCliConfig",
    "ObjectiveRefillDefaults",
    "CodebaseRefillDefaults",
    "RuntimeEnvironmentCallbacks",
    "SupervisorRunHook",
    "SupervisorRuntimeCallbacks",
    "SupervisorRuntimeOperations",
    "TaskProposalRouterConfig",
    "TaskProposalRouterCliConfig",
    "TaskProposalRouterError",
    "TaskProposalRoutePaths",
    "task_metadata_lines",
    "build_task_proposal_route_paths",
]


def __getattr__(name: str):
    if name in {
        "CodebaseFinding",
        "ConfiguredBacklogRecorderBundle",
        "ConfiguredCodebaseScanRecorder",
        "ConfiguredObjectiveBacklogRecorder",
        "ConfiguredRetryBudgetRecorder",
        "build_configured_backlog_recorder_bundle",
        "build_namespace_codebase_scan_recorder",
        "build_namespace_objective_backlog_recorder",
        "build_namespace_retry_budget_recorder",
        "build_task_blocks_ensurer",
        "ensure_task_blocks_present",
        "record_configured_codebase_scan_findings",
        "record_configured_objective_backlog_findings",
        "record_configured_retry_budget_findings",
        "record_codebase_scan_findings",
        "record_objective_backlog_findings",
        "record_retry_budget_findings",
        "run_backlog_refinery",
        "scan_codebase_findings",
    }:
        from . import backlog_refinery

        return getattr(backlog_refinery, name)
    if name in {
        "BundleLaneSpec",
        "launch_bundle_lanes",
        "plan_bundle_lanes",
        "run_bundle_supervisor",
        "write_bundle_lane_manifest",
    }:
        from . import bundle_supervisor

        return getattr(bundle_supervisor, name)
    if name in {"build_merge_prompt", "invoke_llm_resolver", "latest_failed_merge_event", "resolver_payload"}:
        from . import merge_resolver

        return getattr(merge_resolver, name)
    if name in {
        "build_configured_merge_resolver_arg_parser",
        "build_configured_merge_resolver_runner",
        "build_namespace_merge_resolver_runner",
        "build_llm_merge_resolver_invoker",
        "build_merge_prompt_callback",
        "build_resolver_payload_callback",
        "MergeResolverCliConfig",
        "ConfiguredMergeResolverRunner",
        "run_configured_merge_resolver_cli",
    }:
        from . import merge_resolver

        return getattr(merge_resolver, name)
    if name in {"merge_append_only_markdown_sections", "resolve_append_only_markdown_conflicts"}:
        from . import merge_conflict_repair

        return getattr(merge_conflict_repair, name)
    if name in {
        "ActionContractSyncTarget",
        "ActionContractCodegenConfig",
        "build_action_contract_sync_arg_parser",
        "build_action_contract_sync_targets",
        "build_configured_action_contract_sync_runner",
        "ConfiguredActionContractSyncRunner",
        "JavaScriptActionContractConfig",
        "load_action_definitions_from_descriptor",
        "operation_action_mapper",
        "PythonActionContractConfig",
        "render_js_action_contract",
        "render_python_action_contract",
        "run_action_contract_sync",
        "sync_contract_targets",
    }:
        from . import interface_contract_codegen

        return getattr(interface_contract_codegen, name)
    if name == "build_objective_daemon_arg_parser":
        from .objective_daemon import build_arg_parser

        return build_arg_parser
    if name == "run_objective_daemon":
        from .objective_daemon import run_objective_daemon

        return run_objective_daemon
    if name in {
        "default_llm_merge_resolver_command",
        "data_namespace_scan_skip_prefixes",
        "android_validation_command_needs_environment",
        "agent_supervisor_bootstrap_path_entries",
        "AndroidValidationCallbacks",
        "AgentSupervisorRuntimeBootstrapCallbacks",
        "android_validation_environment_contract",
        "agent_supervisor_namespace_paths",
        "apply_env_defaults",
        "apply_environment_contract",
        "BootstrapPathCallbacks",
        "BootstrapPathSpec",
        "CodebaseScanEnvSettings",
        "DEFAULT_REPO_DOCS_DIR",
        "DEFAULT_CODEBASE_SCAN_DATA_SUBDIRS",
        "AGENT_SUPERVISOR_DIRECTORY_BOOTSTRAP_KEYS",
        "AgentSupervisorNamespacePaths",
        "build_agent_supervisor_bootstrap_path_callbacks",
        "build_agent_supervisor_runtime_bootstrap_callbacks",
        "build_android_validation_callbacks",
        "build_bootstrap_path_ensurer",
        "build_bootstrap_path_resolver",
        "build_default_llm_merge_resolver_command_callback",
        "build_prefixed_bootstrap_path_callbacks",
        "build_prefixed_default_llm_merge_resolver_command_callback",
        "build_repo_runtime_environment_callbacks",
        "bootstrap_runtime_environment",
        "build_runtime_environment_callback",
        "build_runtime_environment_callbacks",
        "csv_tuple",
        "env_csv_tuple",
        "env_int",
        "env_path",
        "env_str",
        "environment_assignment_prefix",
        "ensure_named_directories",
        "enforce_android_validation_environment",
        "ensure_runtime_pythonpath",
        "prefixed_bootstrap_path_spec",
        "prefixed_bootstrap_path_specs",
        "prefixed_codebase_scan_env_settings",
        "prefixed_env_csv_tuple",
        "prefixed_env_int",
        "prefixed_env_path",
        "prefixed_env_str",
        "prefixed_env_var",
        "prefixed_interoperability_focus",
        "prefixed_objective_refill_env_settings",
        "ObjectiveRefillEnvSettings",
        "RuntimeEnvironmentCallbacks",
        "repo_external_package_root",
        "repo_external_package_roots",
        "repo_doc_path",
        "repo_root_from_env",
        "repo_relative_or_default",
        "repo_script_command",
        "repo_script_path",
        "repo_task_board_path",
        "resolve_and_ensure_bootstrap_paths",
        "resolve_bootstrap_paths",
        "rewrite_validation_commands",
        "task_board_env_var",
        "task_board_filename",
        "task_board_path_key",
        "task_board_path_option",
        "unique_path_entries",
        "with_android_validation_environment",
        "with_default",
        "with_exclusive_flag_default",
        "with_flag_default",
        "with_repeated_default",
    }:
        from . import wrapper_utils

        return getattr(wrapper_utils, name)
    if name in {
        "common_supervisor_args_from_parsed_args",
        "build_configured_multi_supervisor_launcher",
        "build_configured_multi_supervisor_cli_runner",
        "build_repo_implementation_multi_supervisor_launcher",
        "ConfiguredMultiSupervisorLauncher",
        "ConfiguredMultiSupervisorCliRunner",
        "ImplementationSupervisorTrackConfig",
        "implementation_supervisor_compact_track_spec",
        "implementation_supervisor_compact_track_specs",
        "implementation_supervisor_common_args",
        "implementation_supervisor_namespace_track_config",
        "implementation_supervisor_track_spec",
        "parse_implementation_supervisor_track_spec",
        "parse_supervisor_track_spec",
        "run_supervisor_tracks",
        "SupervisorTrack",
    }:
        from . import multi_supervisor_runner

        if name == "parse_supervisor_track_spec":
            return multi_supervisor_runner.parse_track_spec
        if name == "parse_implementation_supervisor_track_spec":
            return multi_supervisor_runner.parse_implementation_track_spec
        if name == "common_supervisor_args_from_parsed_args":
            return multi_supervisor_runner.common_args_from_parsed_args
        return getattr(multi_supervisor_runner, name)
    if name in {
        "build_supervisor_runtime_operations",
        "build_configured_implementation_supervisor_entrypoint",
        "ConfiguredSupervisorEntrypoint",
        "SupervisorRuntimeOperations",
        "implementation_supervisor_args",
    }:
        from .todo_daemon import supervisor_runtime

        return getattr(supervisor_runtime, name)
    if name in {
        "build_portal_implementation_supervisor_from_args",
        "build_configured_supervisor_bootstrap_runner",
        "build_configured_supervisor_runtime",
        "build_script_supervisor_bootstrap_runner",
        "build_script_supervisor_runtime",
        "ConfiguredSupervisorBootstrapRunner",
        "build_codebase_refill_defaults_from_paths",
        "build_codebase_refill_defaults_factory",
        "build_namespace_codebase_refill_defaults_factory",
        "build_namespace_objective_refill_defaults_factory",
        "build_implementation_supervisor_defaults_from_paths",
        "build_objective_refill_defaults_factory",
        "build_objective_refill_defaults_from_paths",
        "build_supervisor_codebase_scan_refill_callback",
        "build_supervisor_objective_refill_callback",
        "build_supervisor_refill_hooks",
        "build_supervisor_refill_hooks_factory_from_recorders",
        "build_supervisor_refill_hooks_from_recorders",
        "build_supervisor_retry_budget_refill_callback",
        "build_supervisor_runtime_callbacks",
        "configure_supervisor_logging",
        "apply_portal_implementation_supervisor_defaults",
        "apply_portal_implementation_supervisor_defaults_from_paths",
        "run_portal_implementation_supervisor",
        "run_configured_portal_implementation_supervisor",
        "run_configured_portal_implementation_supervisor_with_runtime",
        "ImplementationSupervisorRunContext",
        "ImplementationSupervisorDefaults",
        "ObjectiveRefillDefaults",
        "CodebaseRefillDefaults",
        "SupervisorRunHook",
        "SupervisorRuntimeCallbacks",
        "ConfiguredSupervisorRuntime",
    }:
        from . import implementation_supervisor_runner

        return getattr(implementation_supervisor_runner, name)
    if name in {
        "build_portal_implementation_daemon_from_args",
        "build_configured_daemon_bootstrap_runner",
        "build_configured_implementation_daemon_runner",
        "build_namespace_daemon_bootstrap_runner",
        "build_namespace_configured_implementation_daemon_runner",
        "build_daemon_codebase_scan_refill_callback",
        "build_implementation_daemon_defaults_from_paths",
        "build_daemon_objective_refill_callback",
        "build_daemon_refill_hooks",
        "build_daemon_refill_hooks_factory_from_recorders",
        "build_daemon_refill_hooks_from_recorders",
        "build_daemon_retry_budget_refill_callback",
        "configure_daemon_logging",
        "apply_merge_resolver_environment",
        "apply_portal_implementation_daemon_defaults",
        "apply_portal_implementation_daemon_defaults_from_paths",
        "implementation_state_artifact_paths",
        "namespace_implementation_state_artifact_paths",
        "implementation_state_paths",
        "run_portal_implementation_daemon_loop",
        "run_configured_portal_implementation_daemon",
        "DaemonLoopHook",
        "ConfiguredDaemonBootstrapRunner",
        "ConfiguredImplementationDaemonRunner",
        "ImplementationDaemonRunContext",
        "ImplementationDaemonDefaults",
    }:
        from . import implementation_daemon_runner

        return getattr(implementation_daemon_runner, name)
    if name in {
        "build_task_proposal_prompt",
        "build_task_proposal_prompt_builder",
        "build_task_proposal_route_paths",
        "build_task_proposal_router_cli_config",
        "build_configured_task_proposal_router_runner",
        "build_repo_task_proposal_router_runner",
        "build_repo_task_proposal_route_runner",
        "run_configured_task_proposal_router_cli",
        "run_task_proposal_router",
        "run_task_proposal_router_cli",
        "select_proposal_task",
        "standard_task_proposal_requested_outputs",
        "TaskProposalRouterConfig",
        "TaskProposalRouterCliConfig",
        "TaskProposalRouterError",
        "TaskProposalRoutePaths",
        "ConfiguredTaskProposalRouterRunner",
        "task_metadata_lines",
    }:
        from . import task_proposal_router

        return getattr(task_proposal_router, name)
    raise AttributeError(name)
