"""Autonomous agent supervisor helpers for objective-driven todo execution."""

from .formal_verification_capabilities import (
    DEFAULT_CAPABILITY_CACHE_TTL_SECONDS,
    DEFAULT_CAPABILITY_PROBE_MAX_CHECKS,
    DEFAULT_CAPABILITY_PROBE_TIMEOUT_SECONDS,
    FORMAL_VERIFICATION_CAPABILITY_REPORT_VERSION,
    FORMAL_VERIFICATION_CAPABILITY_SCHEMA_VERSION,
    PROOF_PROVIDER_CAPABILITY_SCHEMA_VERSION,
    CapabilityDimension,
    CapabilityHealth,
    CapabilityHealthCheck,
    FormalVerificationCapabilityProbe,
    FormalVerificationCapabilityReport,
    FormalVerificationProbeConfig,
    FormalVerificationProviderCapability,
    ProofProviderCapability,
    ProofProviderIsolation,
    ProofProviderOperation,
    ProviderCapabilities,
    clear_formal_verification_capability_cache,
    probe_formal_verification_capabilities,
)
from .formal_verification_provider import (
    PROOF_PROVIDER_ENTRY_POINT_GROUP,
    PROOF_PROVIDER_ENVIRONMENT,
    PROOF_PROVIDER_PROTOCOL_VERSION,
    PROOF_PROVIDER_REQUEST_SCHEMA,
    PROOF_PROVIDER_RESPONSE_SCHEMA,
    CancellationToken,
    InProcessProofProvider,
    NetworkAccessDenied,
    ProofProvider,
    ProofProviderError,
    ProofProviderRegistry,
    ProviderClient,
    ProviderFailure,
    ProviderFailureCode,
    ProviderInvocationConfig,
    ProviderInvocationError,
    ProviderRegistration,
    ProviderRequest,
    ProviderResponse,
    SubprocessProofProvider,
    clear_proof_provider_registry,
    discover_proof_providers,
    dispatch_provider_request,
    get_proof_provider,
    register_proof_provider,
    serve_provider_json,
)
from .dataset_store import DatasetArtifact, DatasetAuditSnapshotArtifact, ObjectiveDatasetStore
from .conflict_graph import (
    ConflictEdge,
    ConflictGraph,
    ConflictSurface,
    ConflictWeightHistory,
    LaneAssignment,
    LaneDecision,
    TaskConflictGraph,
    SurfaceContradiction,
    SurfaceContradictionReport,
    SurfaceEvidenceComparison,
    SurfaceEvidenceEdge,
    build_conflict_graph,
    build_conflict_surface,
    color_conflict_graph,
    compare_surface_evidence,
    detect_surface_contradictions,
    materialize_task_conflict_graph,
    update_conflict_weights,
)
from .objective_graph import (
    BundleWriteResult,
    DependencyEdge,
    DependencyRepairEvidence,
    GeneratedObjectiveWork,
    GoalGenerationLimits,
    ObjectiveGenerationLimits,
    ObjectiveGenerationPlan,
    ObjectiveGenerationRejection,
    ObjectiveGenerationResult,
    ObjectiveFinding,
    ObjectiveGoal,
    ObjectiveHeapRecord,
    ObjectiveTaskRecord,
    ObjectiveWorkKind,
    ObjectiveWorkProposal,
    CoverageStatus,
    CoverageSurfaceKind,
    ObjectiveCoverageEdge,
    ObjectiveCoverageGraph,
    TaskDependencyDAG,
    TaskDependencyGraph,
    TaskDependencyNode,
    TaskPlanningGraph,
    TaskScheduleRecord,
    assign_goal_subgoal_packets,
    collect_ast_dataset_records,
    build_bundle_task_payloads,
    canonical_objective_work_identity,
    critical_path_schedule,
    generate_bounded_objective_work,
    generate_objective_todos,
    goal_graph,
    materialize_task_dependency_dag,
    materialize_task_dependency_graph,
    materialize_task_execution_graph,
    materialize_objective_coverage_graph,
    materialize_bounded_objective_work,
    materialize_task_planning_graph,
    objective_finding_conflict_record,
    objective_heap_schedule,
    persist_objective_ast_dataset,
    parse_goal_heap,
    plan_task_lanes,
    plan_semantic_ast_bundles,
    scan_objective_gaps,
    schedule_critical_path,
    semantic_objective_work_key,
    submit_bundle_tasks,
    write_bundle_shards,
)
from .objective_tracker import (
    ObjectiveCompletionResult,
    ObjectiveGoalMigrationResult,
    ObjectiveTrackingResult,
    RepositoryComponent,
    append_interoperability_goals,
    append_refinement_goals,
    build_objective_thought_graph,
    completion_tree_identity,
    discover_gitlink_paths,
    discover_gitmodule_paths,
    discover_repository_components,
    discover_submodule_paths,
    ensure_objective_tracking_document,
    fibonacci_priority,
    migrate_legacy_objective_goals,
    reconcile_objective_goal_completion,
    run_goal_validation,
    write_objective_graph_artifact,
)
from .goal_completion import (
    CONTRADICTION_KINDS,
    GOAL_COMPLETION_MIGRATION_SCHEMA_VERSION,
    LEGACY_COMPLETED_GOAL_STATES,
    CompletionEvidence,
    CompletionGateCheck,
    CompletionGateResult,
    ContradictionEvidence,
    EvidenceValidationResult,
    GoalCompletionDecision,
    GoalLifecycle,
    GoalReopenDecision,
    GoalState,
    GoalTransition,
    IllegalGoalTransition,
    IllegalGoalTransitionError,
    LegacyGoalMigrationDecision,
    ReopenDecision,
    completion_diagnostics,
    discover_goal_contradictions,
    evaluate_goal_completion,
    evaluate_completion_gate,
    legal_goal_transitions,
    is_legacy_completed_goal_state,
    migrate_legacy_goal_completion,
    normalize_goal_state,
    reconcile_goal_reopenings,
    reopen_goal_for_contradictions,
    validate_completion_evidence,
)
from .goal_coverage import (
    AcceptanceCoverage,
    CoverageEdge,
    CoverageSurface,
    FindingAssignment,
    GoalCoverageMap,
    GoalCoverageGraph,
    GoalCoverageEdge,
    MISSING_ACCEPTANCE_CRITERION,
    ValidationReceiptCoverage,
    acceptance_criteria_for_goal,
    attach_findings_to_goals,
    build_goal_coverage_map,
    build_goal_coverage,
    detect_goal_coverage_contradictions,
    generate_goal_work_from_coverage,
    generate_objective_work_seeds,
    goal_coverage_graph,
    goal_coverage_work_seeds,
    normalize_validation_receipt,
    write_goal_coverage_map,
)
from .todo_vector_index import (
    TodoIndexRecord,
    build_execution_packet,
    build_execution_packets,
    build_todo_coverage_inputs,
    cluster_records,
    parse_todo_vector_records,
    split_acceptance_criteria,
    write_todo_vector_index,
)
from .plan_evaluator import (
    ANALYSIS_PROPOSAL_JSON_SCHEMA,
    OBJECTIVE_WORK_EVALUATOR_VERSION,
    PLAN_BRANCH_JSON_SCHEMA,
    PLAN_EVALUATOR_VERSION,
    AnalysisProposal,
    AnalysisProposalEvaluation,
    EvaluatedObjectiveWorkProposal,
    EvaluatedPlanBranch,
    ObjectiveWorkEvaluationPolicy,
    ObjectiveWorkProposalEvaluation,
    PlanBranch,
    PlanBranchValidationError,
    PlanEvaluation,
    RejectedAnalysisProposal,
    RejectedObjectiveWorkProposal,
    evaluate_analysis_proposals,
    evaluate_objective_work_proposals,
    evaluate_plan_branches,
)

__all__ = [
    "PROOF_PROVIDER_CAPABILITY_SCHEMA_VERSION",
    "PROOF_PROVIDER_ENTRY_POINT_GROUP",
    "PROOF_PROVIDER_ENVIRONMENT",
    "PROOF_PROVIDER_PROTOCOL_VERSION",
    "PROOF_PROVIDER_REQUEST_SCHEMA",
    "PROOF_PROVIDER_RESPONSE_SCHEMA",
    "CancellationToken",
    "InProcessProofProvider",
    "NetworkAccessDenied",
    "ProofProvider",
    "ProofProviderCapability",
    "ProofProviderError",
    "ProofProviderIsolation",
    "ProofProviderOperation",
    "ProofProviderRegistry",
    "ProviderCapabilities",
    "ProviderClient",
    "ProviderFailure",
    "ProviderFailureCode",
    "ProviderInvocationConfig",
    "ProviderInvocationError",
    "ProviderRegistration",
    "ProviderRequest",
    "ProviderResponse",
    "SubprocessProofProvider",
    "clear_proof_provider_registry",
    "discover_proof_providers",
    "dispatch_provider_request",
    "get_proof_provider",
    "register_proof_provider",
    "serve_provider_json",
    "CONTRADICTION_KINDS",
    "GOAL_COMPLETION_MIGRATION_SCHEMA_VERSION",
    "LEGACY_COMPLETED_GOAL_STATES",
    "AcceptanceCoverage",
    "ContradictionEvidence",
    "CoverageEdge",
    "CoverageStatus",
    "CoverageSurface",
    "CoverageSurfaceKind",
    "FindingAssignment",
    "GoalCoverageMap",
    "GoalCoverageGraph",
    "GoalCoverageEdge",
    "GoalReopenDecision",
    "MISSING_ACCEPTANCE_CRITERION",
    "GeneratedObjectiveWork",
    "GoalGenerationLimits",
    "ObjectiveGenerationLimits",
    "ObjectiveGenerationPlan",
    "ObjectiveGenerationRejection",
    "ObjectiveGenerationResult",
    "ObjectiveCoverageEdge",
    "ObjectiveCoverageGraph",
    "ObjectiveWorkKind",
    "ObjectiveWorkProposal",
    "OBJECTIVE_GENERATION_ARTIFACT_SCHEMA",
    "SurfaceContradiction",
    "SurfaceContradictionReport",
    "SurfaceEvidenceComparison",
    "SurfaceEvidenceEdge",
    "ValidationReceiptCoverage",
    "acceptance_criteria_for_goal",
    "attach_findings_to_goals",
    "build_goal_coverage_map",
    "build_goal_coverage",
    "build_todo_coverage_inputs",
    "compare_surface_evidence",
    "detect_goal_coverage_contradictions",
    "detect_surface_contradictions",
    "discover_goal_contradictions",
    "generate_goal_work_from_coverage",
    "generate_objective_work_seeds",
    "analysis_proposals_to_objective_work",
    "goal_coverage_graph",
    "goal_coverage_work_seeds",
    "materialize_objective_coverage_graph",
    "load_objective_generation_work",
    "materialize_objective_generation_cycle",
    "normalize_validation_receipt",
    "objective_generation_proposals",
    "persist_objective_generation",
    "split_acceptance_criteria",
    "write_goal_coverage_map",
    "BUNDLE_INDEX_KIND",
    "SCHEDULER_MANIFEST_KIND",
    "QUERY_SCHEMA",
    "QueryArtifactPaths",
    "artifact_schema",
    "ensure_query_database",
    "query_artifact",
    "query_artifact_paths",
    "read_artifact_fields",
    "read_bundle_index_artifact",
    "read_bundle_index_projection",
    "write_bundle_index_artifact",
    "write_queryable_artifact",
    "write_scheduler_manifest_artifact",
    "BundleWriteResult",
    "BundleLaneSpec",
    "DynamicBundleScheduler",
    "AdmissionDecision",
    "HostResourceSnapshot",
    "LaneResourceRequirements",
    "ProviderCapacity",
    "ResourcePolicy",
    "ResourceScheduleSnapshot",
    "ResourceScheduler",
    "ActionContractCodegenConfig",
    "ActionContractSyncSpec",
    "ActionContractSyncTarget",
    "AndroidValidationCallbacks",
    "AgentSupervisorRuntimeBootstrapCallbacks",
    "BootstrapPathCallbacks",
    "BootstrapPathSpec",
    "CodebaseScanEnvSettings",
    "CodebaseFinding",
    "ConfiguredBacklogRecorderBundle",
    "ConfiguredCodebaseScanRecorder",
    "ConfiguredActionContractSyncRunner",
    "ConfiguredDaemonBootstrapRunner",
    "ConfiguredImplementationDaemonRunner",
    "ConfiguredMergeResolverRunner",
    "ConfiguredMultiSupervisorLauncher",
    "ConfiguredMultiSupervisorCliRunner",
    "ConfiguredObjectiveBacklogRecorder",
    "ConfiguredRetryBudgetRecorder",
    "ConfiguredSupervisorBootstrapRunner",
    "ConfiguredSupervisorEntrypoint",
    "ConfiguredSupervisorRuntime",
    "ConfiguredSupervisorRuntimeExports",
    "ConfiguredTaskProposalRouterRunner",
    "completion_tree_identity",
    "StructuredPlanRouterConfig",
    "PlanRoutingResult",
    "ConflictEdge",
    "ConflictGraph",
    "ConflictSurface",
    "ConflictWeightHistory",
    "CompletionEvidence",
    "DatasetArtifact",
    "DatasetAuditSnapshotArtifact",
    "DependencyEdge",
    "DependencyRepairEvidence",
    "DEFAULT_REPO_DOCS_DIR",
    "DEFAULT_CODEBASE_SCAN_DATA_SUBDIRS",
    "AGENT_SUPERVISOR_DIRECTORY_BOOTSTRAP_KEYS",
    "AgentSupervisorNamespacePaths",
    "AgentSupervisorNamespaceContext",
    "ObjectiveFinding",
    "ObjectiveGoal",
    "ObjectiveHeapRecord",
    "ObjectiveDatasetStore",
    "ObjectiveCompletionResult",
    "ObjectiveGoalMigrationResult",
    "EvidenceValidationResult",
    "GoalCompletionDecision",
    "GoalLifecycle",
    "GoalState",
    "GoalTransition",
    "IllegalGoalTransition",
    "IllegalGoalTransitionError",
    "LegacyGoalMigrationDecision",
    "ReopenDecision",
    "ObjectiveTrackingResult",
    "ObjectiveTaskRecord",
    "TaskDependencyDAG",
    "TaskDependencyGraph",
    "TaskDependencyNode",
    "TaskConflictGraph",
    "TaskPlanningGraph",
    "TaskScheduleRecord",
    "LaneAssignment",
    "LaneDecision",
    "PLAN_BRANCH_JSON_SCHEMA",
    "ANALYSIS_PROPOSAL_JSON_SCHEMA",
    "OBJECTIVE_WORK_EVALUATOR_VERSION",
    "PLAN_EVALUATOR_VERSION",
    "EvaluatedObjectiveWorkProposal",
    "EvaluatedPlanBranch",
    "ObjectiveWorkEvaluationPolicy",
    "ObjectiveWorkProposalEvaluation",
    "PlanBranch",
    "PlanBranchValidationError",
    "PlanEvaluation",
    "AnalysisProposal",
    "AnalysisProposalEvaluation",
    "RejectedAnalysisProposal",
    "RejectedObjectiveWorkProposal",
    "ObjectiveRefillEnvSettings",
    "RepositoryComponent",
    "append_interoperability_goals",
    "append_refinement_goals",
    "android_validation_command_needs_environment",
    "android_validation_environment_contract",
    "agent_supervisor_bootstrap_path_entries",
    "agent_supervisor_namespace_paths",
    "apply_env_defaults",
    "apply_environment_contract",
    "assign_goal_subgoal_packets",
    "build_bundle_task_payloads",
    "build_conflict_graph",
    "build_conflict_surface",
    "build_configured_backlog_recorder_bundle",
    "build_action_contract_sync_runner_from_spec",
    "build_configured_action_contract_sync_runner",
    "build_execution_packet",
    "build_execution_packets",
    "build_action_contract_sync_arg_parser",
    "build_action_contract_sync_targets",
    "build_merge_prompt",
    "build_configured_merge_resolver_arg_parser",
    "build_configured_merge_resolver_runner",
    "build_namespace_merge_resolver_runner",
    "build_namespace_merge_resolver_runner_from_spec",
    "build_configured_daemon_bootstrap_runner",
    "build_configured_implementation_daemon_runner",
    "build_namespace_daemon_bootstrap_runner",
    "build_namespace_configured_implementation_daemon_runner",
    "build_configured_multi_supervisor_launcher",
    "build_configured_multi_supervisor_cli_runner",
    "build_repo_implementation_multi_supervisor_launcher",
    "build_configured_implementation_supervisor_entrypoint",
    "build_module_implementation_supervisor_entrypoint",
    "build_configured_supervisor_bootstrap_runner",
    "build_configured_supervisor_runtime",
    "build_configured_supervisor_runtime_exports",
    "build_script_supervisor_bootstrap_runner",
    "build_script_supervisor_runtime",
    "build_configured_task_proposal_router_runner",
    "build_structured_plan_prompt",
    "build_llm_merge_resolver_invoker",
    "llm_merge_resolver_fallback_command",
    "build_merge_prompt_callback",
    "build_namespace_codebase_scan_recorder",
    "build_objective_daemon_arg_parser",
    "build_namespace_objective_backlog_recorder",
    "build_namespace_retry_budget_recorder",
    "build_objective_thought_graph",
    "build_resolver_payload_callback",
    "build_bootstrap_path_ensurer",
    "build_bootstrap_path_resolver",
    "build_agent_supervisor_bootstrap_path_callbacks",
    "build_agent_supervisor_namespace_context",
    "build_agent_supervisor_runtime_bootstrap_callbacks",
    "build_prefixed_bootstrap_path_callbacks",
    "build_android_validation_callbacks",
    "build_default_llm_merge_resolver_command_callback",
    "build_prefixed_default_llm_merge_resolver_command_callback",
    "build_repo_runtime_environment_callbacks",
    "build_runtime_environment_callback",
    "build_runtime_environment_callbacks",
    "collect_ast_dataset_records",
    "critical_path_schedule",
    "color_conflict_graph",
    "cluster_records",
    "generate_objective_todos",
    "generate_bounded_objective_work",
    "generate_structured_plan_branches",
    "ensure_objective_tracking_document",
    "discover_gitlink_paths",
    "discover_gitmodule_paths",
    "discover_repository_components",
    "discover_submodule_paths",
    "csv_tuple",
    "default_llm_merge_resolver_command",
    "data_namespace_scan_skip_prefixes",
    "env_csv_tuple",
    "env_int",
    "env_path",
    "env_str",
    "environment_assignment_prefix",
    "ensure_named_directories",
    "ensure_task_blocks_present",
    "enforce_android_validation_environment",
    "ensure_runtime_pythonpath",
    "evaluate_plan_branches",
    "evaluate_analysis_proposals",
    "evaluate_objective_work_proposals",
    "fibonacci_priority",
    "goal_graph",
    "canonical_objective_work_identity",
    "materialize_bounded_objective_work",
    "materialize_task_dependency_dag",
    "materialize_task_dependency_graph",
    "materialize_task_conflict_graph",
    "materialize_task_execution_graph",
    "materialize_task_planning_graph",
    "objective_finding_conflict_record",
    "objective_heap_schedule",
    "semantic_objective_work_key",
    "launch_bundle_lanes",
    "LeaseCoordinator",
    "LeaseGrant",
    "LeaseQueueBridge",
    "LeasedQueuedTask",
    "TaskLeaseState",
    "LeasedLaneResult",
    "LeaseConflictError",
    "DependencyNotReadyError",
    "LeaseError",
    "LeaseExpiredError",
    "TaskIdentity",
    "StaleFencingTokenError",
    "adapt_goal_bundle",
    "canonical_bundle_identity",
    "canonical_task_identity",
    "invoke_llm_resolver",
    "JavaScriptActionContractConfig",
    "latest_failed_merge_event",
    "load_action_definitions_from_descriptor",
    "operation_action_mapper",
    "parse_goal_heap",
    "plan_task_lanes",
    "parse_structured_plan_branches",
    "deterministic_plan_branches",
    "parse_todo_vector_records",
    "plan_semantic_ast_bundles",
    "plan_bundle_lanes",
    "normalize_provider_capacities",
    "normalize_provider_capacity",
    "sample_host_resources",
    "schedule_critical_path",
    "prefixed_bootstrap_path_spec",
    "prefixed_bootstrap_path_specs",
    "prefixed_codebase_scan_env_settings",
    "prefixed_env_csv_tuple",
    "prefixed_env_int",
    "prefixed_env_path",
    "prefixed_env_str",
    "prefixed_env_var",
    "prefixed_interoperability_focus",
    "prefixed_objective_refill_env_settings",
    "PythonActionContractConfig",
    "persist_objective_ast_dataset",
    "record_configured_codebase_scan_findings",
    "record_configured_objective_backlog_findings",
    "record_configured_retry_budget_findings",
    "record_codebase_scan_findings",
    "record_objective_backlog_findings",
    "record_retry_budget_findings",
    "reconcile_goal_reopenings",
    "reconcile_objective_goal_completion",
    "reopen_goal_for_contradictions",
    "CompletionGateCheck",
    "CompletionGateResult",
    "evaluate_completion_gate",
    "evaluate_goal_completion",
    "completion_diagnostics",
    "is_legacy_completed_goal_state",
    "legal_goal_transitions",
    "migrate_legacy_goal_completion",
    "migrate_legacy_objective_goals",
    "normalize_goal_state",
    "validate_completion_evidence",
    "repo_external_package_root",
    "repo_external_package_roots",
    "repo_doc_path",
    "repo_root_from_env",
    "repo_relative_or_default",
    "repo_script_command",
    "repo_script_path",
    "repo_task_board_path",
    "render_js_action_contract",
    "render_python_action_contract",
    "resolve_and_ensure_bootstrap_paths",
    "resolve_bootstrap_paths",
    "resolve_append_only_markdown_conflicts",
    "resolver_payload",
    "run_backlog_refinery",
    "run_action_contract_sync",
    "run_goal_validation",
    "run_bundle_supervisor",
    "run_objective_daemon",
    "scan_codebase_findings",
    "scan_objective_gaps",
    "submit_bundle_tasks",
    "update_conflict_weights",
    "sync_contract_targets",
    "task_board_env_var",
    "task_board_filename",
    "task_board_path_key",
    "task_board_path_option",
    "write_objective_graph_artifact",
    "write_bundle_shards",
    "write_bundle_lane_manifest",
    "write_todo_vector_index",
    "unique_path_entries",
    "with_android_validation_environment",
    "with_default",
    "with_exclusive_flag_default",
    "with_flag_default",
    "with_repeated_default",
    "TodoIndexRecord",
    "merge_append_only_markdown_sections",
    "common_supervisor_args_from_parsed_args",
    "ImplementationSupervisorNamespaceTrackSpec",
    "implementation_supervisor_compact_track_spec",
    "implementation_supervisor_compact_track_specs",
    "implementation_supervisor_common_args",
    "implementation_multi_supervisor_env_defaults",
    "implementation_supervisor_namespace_track_config",
    "implementation_supervisor_namespace_track_configs",
    "implementation_supervisor_track_spec",
    "dynamic_bundle_scheduler_track",
    "parse_implementation_supervisor_track_spec",
    "parse_supervisor_track_spec",
    "run_supervisor_tracks",
    "run_leased_lane",
    "run_leased_lane_result",
    "SupervisorTrack",
    "build_task_proposal_prompt",
    "build_task_proposal_prompt_builder",
    "build_task_proposal_router_cli_config",
    "build_repo_task_proposal_router_runner",
    "build_repo_task_proposal_route_runner",
    "build_repo_task_proposal_route_runner_from_spec",
    "build_task_blocks_ensurer",
    "build_codebase_refill_defaults_from_paths",
    "build_namespace_codebase_refill_defaults_factory",
    "build_namespace_objective_refill_defaults_factory",
    "build_portal_implementation_daemon_from_args",
    "build_portal_implementation_supervisor_from_args",
    "build_daemon_refill_hooks",
    "build_daemon_refill_hooks_factory_from_recorders",
    "build_daemon_refill_hooks_from_recorders",
    "build_daemon_codebase_scan_refill_callback",
    "build_implementation_daemon_defaults_from_paths",
    "build_implementation_supervisor_defaults_from_paths",
    "build_objective_refill_defaults_factory",
    "build_objective_refill_defaults_from_paths",
    "build_daemon_objective_refill_callback",
    "build_daemon_retry_budget_refill_callback",
    "build_codebase_refill_defaults_factory",
    "build_supervisor_refill_hooks",
    "build_supervisor_refill_hooks_factory_from_recorders",
    "build_supervisor_refill_hooks_from_recorders",
    "build_supervisor_codebase_scan_refill_callback",
    "build_supervisor_objective_refill_callback",
    "build_supervisor_retry_budget_refill_callback",
    "build_supervisor_runtime_callbacks",
    "build_supervisor_runtime_operations",
    "bootstrap_runtime_environment",
    "configure_daemon_logging",
    "configure_supervisor_logging",
    "apply_merge_resolver_environment",
    "apply_portal_implementation_daemon_defaults",
    "apply_portal_implementation_daemon_defaults_from_paths",
    "apply_portal_implementation_supervisor_defaults",
    "apply_portal_implementation_supervisor_defaults_from_paths",
    "implementation_state_artifact_paths",
    "namespace_implementation_state_artifact_paths",
    "implementation_state_paths",
    "implementation_supervisor_args",
    "run_portal_implementation_daemon_loop",
    "run_portal_implementation_supervisor",
    "run_configured_portal_implementation_daemon",
    "run_configured_portal_implementation_supervisor",
    "run_configured_portal_implementation_supervisor_with_runtime",
    "run_configured_merge_resolver_cli",
    "run_configured_task_proposal_router_cli",
    "run_task_proposal_router",
    "run_task_proposal_router_cli",
    "rewrite_validation_commands",
    "select_proposal_task",
    "standard_task_proposal_requested_outputs",
    "DaemonLoopHook",
    "ImplementationDaemonRunContext",
    "ImplementationDaemonDefaults",
    "ImplementationSupervisorTrackConfig",
    "ImplementationSupervisorRunContext",
    "ImplementationSupervisorDefaults",
    "MergeResolverCliConfig",
    "MergeResolverNamespaceSpec",
    "ObjectiveRefillDefaults",
    "CodebaseRefillDefaults",
    "RuntimeEnvironmentCallbacks",
    "SupervisorRunHook",
    "SupervisorRuntimeCallbacks",
    "SupervisorRuntimeOperations",
    "TaskProposalRouterConfig",
    "TaskProposalRouterCliConfig",
    "TaskProposalRouterError",
    "TaskProposalRoutePaths",
    "TaskProposalRouteSpec",
    "AuditFindingRecord",
    "AuditFindingStatus",
    "AuditScanResult",
    "AnalysisEscalationPolicy",
    "AnalysisEscalationRecord",
    "AnalysisEscalationResult",
    "AnalysisEscalationStage",
    "AnalysisEscalationStatus",
    "AstCoverageReport",
    "AnalysisProposalRoutingResult",
    "ExhaustionBinding",
    "ExhaustionQuorumResult",
    "audit_codebase_findings",
    "evaluate_exhaustion_quorum",
    "run_audit_scan",
    "run_exhaustive_ast_coverage",
    "run_low_backlog_analysis",
    "run_analysis_escalation",
    "generate_analysis_proposals",
    "parse_analysis_proposals",
    "build_analysis_proposal_prompt",
    "record_codebase_audit_findings",
    "task_metadata_lines",
    "build_task_proposal_route_paths",
]


def __getattr__(name: str):
    if name in {
        "BUNDLE_INDEX_KIND",
        "SCHEDULER_MANIFEST_KIND",
        "QUERY_SCHEMA",
        "QueryArtifactPaths",
        "artifact_schema",
        "ensure_query_database",
        "query_artifact",
        "query_artifact_paths",
        "read_artifact_fields",
        "read_bundle_index_artifact",
        "read_bundle_index_projection",
        "write_bundle_index_artifact",
        "write_queryable_artifact",
        "write_scheduler_manifest_artifact",
    }:
        from . import artifact_store

        return getattr(artifact_store, name)
    if name in {
        "AuditFindingRecord",
        "AuditFindingStatus",
        "AuditScanResult",
        "audit_codebase_findings",
        "run_audit_scan",
        "AnalysisEscalationResult",
        "AstCoverageReport",
        "run_exhaustive_ast_coverage",
        "run_low_backlog_analysis",
        "run_analysis_escalation",
    }:
        from . import audit_scanner

        return getattr(audit_scanner, name)
    if name in {
        "AnalysisEscalationPolicy",
        "AnalysisEscalationRecord",
        "AnalysisEscalationStage",
        "AnalysisEscalationStatus",
    }:
        from . import analyzer_health

        return getattr(analyzer_health, name)
    if name in {
        "ExhaustionBinding",
        "ExhaustionQuorumResult",
        "evaluate_exhaustion_quorum",
    }:
        from . import scan_receipts

        return getattr(scan_receipts, name)
    if name in {
        "CodebaseFinding",
        "ConfiguredBacklogRecorderBundle",
        "ConfiguredCodebaseScanRecorder",
        "ConfiguredObjectiveBacklogRecorder",
        "ConfiguredRetryBudgetRecorder",
        "build_configured_backlog_recorder_bundle",
        "build_namespace_codebase_scan_recorder",
        "build_namespace_objective_backlog_recorder",
        "build_namespace_retry_budget_recorder",
        "build_task_blocks_ensurer",
        "ensure_task_blocks_present",
        "record_configured_codebase_scan_findings",
        "record_configured_objective_backlog_findings",
        "record_configured_retry_budget_findings",
        "record_codebase_scan_findings",
        "record_codebase_audit_findings",
        "record_objective_backlog_findings",
        "record_retry_budget_findings",
        "run_backlog_refinery",
        "scan_codebase_findings",
    }:
        from . import backlog_refinery

        return getattr(backlog_refinery, name)
    if name in {
        "BundleLaneSpec",
        "DynamicBundleScheduler",
        "launch_bundle_lanes",
        "plan_bundle_lanes",
        "run_bundle_supervisor",
        "write_bundle_lane_manifest",
    }:
        from . import bundle_supervisor

        return getattr(bundle_supervisor, name)
    if name in {
        "AdmissionDecision",
        "HostResourceSnapshot",
        "LaneResourceRequirements",
        "ProviderCapacity",
        "ResourcePolicy",
        "ResourceScheduleSnapshot",
        "ResourceScheduler",
        "normalize_provider_capacities",
        "normalize_provider_capacity",
        "sample_host_resources",
    }:
        from . import resource_scheduler

        return getattr(resource_scheduler, name)
    if name in {
        "TaskIdentity",
        "canonical_bundle_identity",
        "canonical_task_identity",
    }:
        from . import task_identity

        return getattr(task_identity, name)
    if name in {
        "DependencyNotReadyError",
        "LeaseConflictError",
        "LeaseCoordinator",
        "LeaseError",
        "LeaseExpiredError",
        "LeaseGrant",
        "LeaseQueueBridge",
        "LeasedQueuedTask",
        "TaskLeaseState",
        "StaleFencingTokenError",
        "adapt_goal_bundle",
    }:
        from . import lease_coordination

        return getattr(lease_coordination, name)
    if name in {
        "LeasedLaneResult",
        "run_leased_lane",
        "run_leased_lane_result",
    }:
        from . import leased_lane

        return getattr(leased_lane, name)
    if name in {"build_merge_prompt", "invoke_llm_resolver", "latest_failed_merge_event", "resolver_payload"}:
        from . import merge_resolver

        return getattr(merge_resolver, name)
    if name in {
        "llm_merge_resolver_fallback_command",
    }:
        from . import llm_merge_resolver_fallback

        return getattr(llm_merge_resolver_fallback, name)
    if name in {
        "build_configured_merge_resolver_arg_parser",
        "build_configured_merge_resolver_runner",
        "build_namespace_merge_resolver_runner",
        "build_namespace_merge_resolver_runner_from_spec",
        "build_llm_merge_resolver_invoker",
        "build_merge_prompt_callback",
        "build_resolver_payload_callback",
        "MergeResolverCliConfig",
        "MergeResolverNamespaceSpec",
        "ConfiguredMergeResolverRunner",
        "run_configured_merge_resolver_cli",
    }:
        from . import merge_resolver

        return getattr(merge_resolver, name)
    if name in {"merge_append_only_markdown_sections", "resolve_append_only_markdown_conflicts"}:
        from . import merge_conflict_repair

        return getattr(merge_conflict_repair, name)
    if name in {
        "ActionContractSyncTarget",
        "ActionContractSyncSpec",
        "ActionContractCodegenConfig",
        "build_action_contract_sync_arg_parser",
        "build_action_contract_sync_runner_from_spec",
        "build_action_contract_sync_targets",
        "build_configured_action_contract_sync_runner",
        "ConfiguredActionContractSyncRunner",
        "JavaScriptActionContractConfig",
        "load_action_definitions_from_descriptor",
        "operation_action_mapper",
        "PythonActionContractConfig",
        "render_js_action_contract",
        "render_python_action_contract",
        "run_action_contract_sync",
        "sync_contract_targets",
    }:
        from . import interface_contract_codegen

        return getattr(interface_contract_codegen, name)
    if name == "build_objective_daemon_arg_parser":
        from .objective_daemon import build_arg_parser

        return build_arg_parser
    if name == "run_objective_daemon":
        from .objective_daemon import run_objective_daemon

        return run_objective_daemon
    if name in {
        "OBJECTIVE_GENERATION_ARTIFACT_SCHEMA",
        "load_objective_generation_work",
        "materialize_objective_generation_cycle",
        "objective_generation_proposals",
        "persist_objective_generation",
    }:
        from . import objective_daemon

        return getattr(objective_daemon, name)
    if name in {
        "default_llm_merge_resolver_command",
        "data_namespace_scan_skip_prefixes",
        "android_validation_command_needs_environment",
        "agent_supervisor_bootstrap_path_entries",
        "AndroidValidationCallbacks",
        "AgentSupervisorRuntimeBootstrapCallbacks",
        "android_validation_environment_contract",
        "agent_supervisor_namespace_paths",
        "apply_env_defaults",
        "apply_environment_contract",
        "BootstrapPathCallbacks",
        "BootstrapPathSpec",
        "CodebaseScanEnvSettings",
        "DEFAULT_REPO_DOCS_DIR",
        "DEFAULT_CODEBASE_SCAN_DATA_SUBDIRS",
        "AGENT_SUPERVISOR_DIRECTORY_BOOTSTRAP_KEYS",
        "AgentSupervisorNamespacePaths",
        "AgentSupervisorNamespaceContext",
        "build_agent_supervisor_bootstrap_path_callbacks",
        "build_agent_supervisor_namespace_context",
        "build_agent_supervisor_runtime_bootstrap_callbacks",
        "build_android_validation_callbacks",
        "build_bootstrap_path_ensurer",
        "build_bootstrap_path_resolver",
        "build_default_llm_merge_resolver_command_callback",
        "build_prefixed_bootstrap_path_callbacks",
        "build_prefixed_default_llm_merge_resolver_command_callback",
        "build_repo_runtime_environment_callbacks",
        "bootstrap_runtime_environment",
        "build_runtime_environment_callback",
        "build_runtime_environment_callbacks",
        "csv_tuple",
        "env_csv_tuple",
        "env_int",
        "env_path",
        "env_str",
        "environment_assignment_prefix",
        "ensure_named_directories",
        "enforce_android_validation_environment",
        "ensure_runtime_pythonpath",
        "prefixed_bootstrap_path_spec",
        "prefixed_bootstrap_path_specs",
        "prefixed_codebase_scan_env_settings",
        "prefixed_env_csv_tuple",
        "prefixed_env_int",
        "prefixed_env_path",
        "prefixed_env_str",
        "prefixed_env_var",
        "prefixed_interoperability_focus",
        "prefixed_objective_refill_env_settings",
        "ObjectiveRefillEnvSettings",
        "RuntimeEnvironmentCallbacks",
        "repo_external_package_root",
        "repo_external_package_roots",
        "repo_doc_path",
        "repo_root_from_env",
        "repo_relative_or_default",
        "repo_script_command",
        "repo_script_path",
        "repo_task_board_path",
        "resolve_and_ensure_bootstrap_paths",
        "resolve_bootstrap_paths",
        "rewrite_validation_commands",
        "task_board_env_var",
        "task_board_filename",
        "task_board_path_key",
        "task_board_path_option",
        "unique_path_entries",
        "with_android_validation_environment",
        "with_default",
        "with_exclusive_flag_default",
        "with_flag_default",
        "with_repeated_default",
    }:
        from . import wrapper_utils

        return getattr(wrapper_utils, name)
    if name in {
        "common_supervisor_args_from_parsed_args",
        "build_configured_multi_supervisor_launcher",
        "build_configured_multi_supervisor_cli_runner",
        "build_repo_implementation_multi_supervisor_launcher",
        "ConfiguredMultiSupervisorLauncher",
        "ConfiguredMultiSupervisorCliRunner",
        "ImplementationSupervisorNamespaceTrackSpec",
        "ImplementationSupervisorTrackConfig",
        "implementation_supervisor_compact_track_spec",
        "implementation_supervisor_compact_track_specs",
        "implementation_supervisor_common_args",
        "implementation_multi_supervisor_env_defaults",
        "implementation_supervisor_namespace_track_config",
        "implementation_supervisor_namespace_track_configs",
        "implementation_supervisor_track_spec",
        "dynamic_bundle_scheduler_track",
        "parse_implementation_supervisor_track_spec",
        "parse_supervisor_track_spec",
        "run_supervisor_tracks",
        "SupervisorTrack",
    }:
        from . import multi_supervisor_runner

        if name == "parse_supervisor_track_spec":
            return multi_supervisor_runner.parse_track_spec
        if name == "parse_implementation_supervisor_track_spec":
            return multi_supervisor_runner.parse_implementation_track_spec
        if name == "common_supervisor_args_from_parsed_args":
            return multi_supervisor_runner.common_args_from_parsed_args
        return getattr(multi_supervisor_runner, name)
    if name in {
        "build_supervisor_runtime_operations",
        "build_configured_implementation_supervisor_entrypoint",
        "build_module_implementation_supervisor_entrypoint",
        "ConfiguredSupervisorEntrypoint",
        "SupervisorRuntimeOperations",
        "implementation_supervisor_args",
    }:
        from .todo_daemon import supervisor_runtime

        return getattr(supervisor_runtime, name)
    if name in {
        "build_portal_implementation_supervisor_from_args",
        "build_configured_supervisor_bootstrap_runner",
        "build_configured_supervisor_runtime",
        "build_configured_supervisor_runtime_exports",
        "build_script_supervisor_bootstrap_runner",
        "build_script_supervisor_runtime",
        "ConfiguredSupervisorBootstrapRunner",
        "ConfiguredSupervisorRuntimeExports",
        "build_codebase_refill_defaults_from_paths",
        "build_codebase_refill_defaults_factory",
        "build_namespace_codebase_refill_defaults_factory",
        "build_namespace_objective_refill_defaults_factory",
        "build_implementation_supervisor_defaults_from_paths",
        "build_objective_refill_defaults_factory",
        "build_objective_refill_defaults_from_paths",
        "build_supervisor_codebase_scan_refill_callback",
        "build_supervisor_objective_refill_callback",
        "build_supervisor_refill_hooks",
        "build_supervisor_refill_hooks_factory_from_recorders",
        "build_supervisor_refill_hooks_from_recorders",
        "build_supervisor_retry_budget_refill_callback",
        "build_supervisor_runtime_callbacks",
        "configure_supervisor_logging",
        "apply_portal_implementation_supervisor_defaults",
        "apply_portal_implementation_supervisor_defaults_from_paths",
        "run_portal_implementation_supervisor",
        "run_configured_portal_implementation_supervisor",
        "run_configured_portal_implementation_supervisor_with_runtime",
        "ImplementationSupervisorRunContext",
        "ImplementationSupervisorDefaults",
        "ObjectiveRefillDefaults",
        "CodebaseRefillDefaults",
        "SupervisorRunHook",
        "SupervisorRuntimeCallbacks",
        "ConfiguredSupervisorRuntime",
    }:
        from . import implementation_supervisor_runner

        return getattr(implementation_supervisor_runner, name)
    if name in {
        "build_portal_implementation_daemon_from_args",
        "build_configured_daemon_bootstrap_runner",
        "build_configured_implementation_daemon_runner",
        "build_namespace_daemon_bootstrap_runner",
        "build_namespace_configured_implementation_daemon_runner",
        "build_daemon_codebase_scan_refill_callback",
        "build_implementation_daemon_defaults_from_paths",
        "build_daemon_objective_refill_callback",
        "build_daemon_refill_hooks",
        "build_daemon_refill_hooks_factory_from_recorders",
        "build_daemon_refill_hooks_from_recorders",
        "build_daemon_retry_budget_refill_callback",
        "configure_daemon_logging",
        "apply_merge_resolver_environment",
        "apply_portal_implementation_daemon_defaults",
        "apply_portal_implementation_daemon_defaults_from_paths",
        "implementation_state_artifact_paths",
        "namespace_implementation_state_artifact_paths",
        "implementation_state_paths",
        "run_portal_implementation_daemon_loop",
        "run_configured_portal_implementation_daemon",
        "DaemonLoopHook",
        "ConfiguredDaemonBootstrapRunner",
        "ConfiguredImplementationDaemonRunner",
        "ImplementationDaemonRunContext",
        "ImplementationDaemonDefaults",
    }:
        from . import implementation_daemon_runner

        return getattr(implementation_daemon_runner, name)
    if name in {
        "build_task_proposal_prompt",
        "build_task_proposal_prompt_builder",
        "build_structured_plan_prompt",
        "build_task_proposal_route_paths",
        "build_task_proposal_router_cli_config",
        "build_configured_task_proposal_router_runner",
        "build_repo_task_proposal_router_runner",
        "build_repo_task_proposal_route_runner",
        "build_repo_task_proposal_route_runner_from_spec",
        "run_configured_task_proposal_router_cli",
        "run_task_proposal_router",
        "run_task_proposal_router_cli",
        "generate_structured_plan_branches",
        "parse_structured_plan_branches",
        "deterministic_plan_branches",
        "select_proposal_task",
        "standard_task_proposal_requested_outputs",
        "TaskProposalRouterConfig",
        "TaskProposalRouterCliConfig",
        "TaskProposalRouterError",
        "TaskProposalRoutePaths",
        "TaskProposalRouteSpec",
        "ConfiguredTaskProposalRouterRunner",
        "StructuredPlanRouterConfig",
        "PlanRoutingResult",
        "AnalysisProposalRoutingResult",
        "build_analysis_proposal_prompt",
        "analysis_proposals_to_objective_work",
        "generate_analysis_proposals",
        "parse_analysis_proposals",
        "task_metadata_lines",
    }:
        from . import task_proposal_router

        return getattr(task_proposal_router, name)
    raise AttributeError(name)
from .codex_failure_policy import (
    COMPLETED_PATCH_STATUSES,
    TRANSIENT_MAIN_APPLY_STATUSES,
    TRANSIENT_PATCH_STATUSES,
    CodexProgramOutcome,
    classify_codex_program_outcome,
)
