[build]
target = "aarch64-pc-windows-msvc"

[target.aarch64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/NODEFAULTLIB:libcmt.lib",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\arm64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\arm64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\km\\arm64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\lib\\arm64",
    "-C", "link-args=/DEFAULTLIB:kernel32.lib /DEFAULTLIB:user32.lib /DEFAULTLIB:advapi32.lib"
]

[env]
PYTHON_SYS_EXECUTABLE = { value = "python", relative = true }
PYO3_PYTHON = { value = "python", relative = true }
VSINSTALLDIR = { value = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community", relative = false }
VCToolsInstallDir = { value = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130", relative = false }
WindowsSdkDir = { value = "C:\\Program Files (x86)\\Windows Kits\\10", relative = false }

[build.env]
VIRTUAL_ENV = { value = "${VIRTUAL_ENV}", relative = false }
PATH = { value = "${VIRTUAL_ENV}/Scripts;${PATH}", relative = false, force = true }