"""Live Vampire + E semantic certification (FVT-054 / FVT-G207).

``ATPLiveSemanticCertification@1``

Replaces SZS parser fixtures with real pinned ATP runs while preserving
reconstruction and kernel-checking ceilings.

Acceptance covered:

* Vampire and E each execute theorem and counter-satisfiable problems,
  premise/conclusion mutations, replay, malformed TPTP, timeout/resource
  bounds, disagreement, and proof-object/reconstruction cases;
* receipts bind exact binary and artifact digests, TPTP source, assumptions,
  conclusion, limits, raw SZS output, and reconstruction status;
* an ATP result cannot exceed candidate/reconstruction authority until
  checked by a trusted kernel;
* fixture/parser-only evidence cannot satisfy the live goal;
* certification never installs, downloads, or opens the network.
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
ATP_CERT_PATH = REPO_ROOT / "tools" / "logic" / "certification" / "atp.py"
LIVE_CERTIFICATE_PATH = (
    REPO_ROOT / "docs" / "architecture" / "formal_verification_atp_live_certificate.json"
)
LOCK_PATH = REPO_ROOT / "config" / "formal_verification_toolchains.lock.json"

LIVE_INTERFACE = "ATPLiveSemanticCertification@1"
LIVE_SCHEMA_VERSION = "atp-live-semantic-certification/v1"
LIVE_CORPUS_SCHEMA = "atp-live-semantic-corpus/v1"
LIVE_GOAL_ID = "FVT-G207"
LIVE_TASK_ID = "FVT-054"
LOCKED_VAMPIRE_VERSION = "5.0.1"
LOCKED_EPROVER_VERSION = "3.2.5"

REQUIRED_CASE_KINDS = {
    "theorem",
    "counter_satisfiable",
    "mutation",
    "replay",
    "malformed",
    "timeout",
    "disagreement",
    "proof_object",
    "reconstruction",
}

REQUIRED_CASE_IDS = {
    "theorem",
    "counter_satisfiable",
    "mutated_premise",
    "mutated_conclusion",
    "proof_object",
    "replay",
    "malformed_tptp",
    "timeout_resource_bounds",
    "reconstruction",
    "disagreement",
}

REQUIRED_BINDING_FIELDS = {
    "binary_digest",
    "artifact_digest",
    "source_digest",
    "assumptions",
    "conclusion",
    "limits",
    "reconstruction_status",
    "raw_szs_output_digest",
}


def _ensure_import_paths() -> None:
    datasets_root = REPO_ROOT / "ipfs_datasets_py"
    for candidate in (str(REPO_ROOT), str(datasets_root)):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)


def _load_module(path: Path, name: str):
    assert path.is_file(), f"missing expected output: {path}"
    _ensure_import_paths()
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def atp_cert():
    return _load_module(ATP_CERT_PATH, "tools_logic_certification_atp_live")


@pytest.fixture(scope="module")
def offline_env(atp_cert) -> dict[str, str]:
    # Prefer managed theorem-prover bins without install or network.
    return atp_cert.managed_execution_env(os.environ)


@pytest.fixture(scope="module")
def live_receipt(atp_cert, offline_env) -> dict[str, Any]:
    return atp_cert.build_live_semantic_receipt(
        repo_root=REPO_ROOT,
        env=offline_env,
    )


@pytest.fixture(scope="module")
def live_certificate(atp_cert, live_receipt, offline_env) -> dict[str, Any]:
    """Ensure the durable certificate exists and load it.

    Tool-less re-runs must not demote a prior production live certificate
    (objective validation repair).
    """

    path = atp_cert.write_live_certificate(
        live_receipt,
        repo_root=REPO_ROOT,
        env=offline_env,
    )
    assert path.is_file()
    assert path == LIVE_CERTIFICATE_PATH or path.resolve() == LIVE_CERTIFICATE_PATH.resolve()
    payload = json.loads(LIVE_CERTIFICATE_PATH.read_text(encoding="utf-8"))
    assert isinstance(payload, dict)
    return payload


# ---------------------------------------------------------------------------
# Expected outputs
# ---------------------------------------------------------------------------


def test_expected_outputs_exist() -> None:
    assert ATP_CERT_PATH.is_file()
    assert Path(__file__).is_file()
    # Certificate may be generated by the suite fixture; require path declared.
    assert (
        REPO_ROOT / "docs" / "architecture" / "formal_verification_atp_live_certificate.json"
    ).parent.is_dir()


def test_live_module_constants(atp_cert) -> None:
    assert atp_cert.LIVE_INTERFACE == LIVE_INTERFACE
    assert atp_cert.LIVE_SCHEMA_VERSION == LIVE_SCHEMA_VERSION
    assert atp_cert.LIVE_CORPUS_SCHEMA == LIVE_CORPUS_SCHEMA
    assert atp_cert.LIVE_GOAL_ID == LIVE_GOAL_ID
    assert atp_cert.LIVE_TASK_ID == LIVE_TASK_ID
    assert atp_cert.LOCKED_VAMPIRE_VERSION == LOCKED_VAMPIRE_VERSION
    assert atp_cert.LOCKED_EPROVER_VERSION == LOCKED_EPROVER_VERSION
    assert atp_cert.AUTHORITY_SCOPE == "atp_candidate_until_kernel_reconstruction"
    assert atp_cert.AUTHORITY_CEILING == "reconstruction"
    assert atp_cert.DEFAULT_LIVE_CERTIFICATE_RELATIVE.as_posix().endswith(
        "formal_verification_atp_live_certificate.json"
    )


def test_live_corpus_schema_and_required_cases(atp_cert) -> None:
    manifest = atp_cert.default_live_corpus_manifest()
    assert manifest["schema_version"] == LIVE_CORPUS_SCHEMA
    assert manifest["interface"] == LIVE_INTERFACE
    assert manifest["goal_id"] == LIVE_GOAL_ID
    assert manifest["task_id"] == LIVE_TASK_ID
    assert manifest["locked_vampire_version"] == LOCKED_VAMPIRE_VERSION
    assert manifest["locked_eprover_version"] == LOCKED_EPROVER_VERSION
    assert manifest["policy"]["results_are_candidates_without_reconstruction"] is True
    assert manifest["policy"][
        "kernel_reconstruction_required_for_theorem_authority"
    ] is True
    assert manifest["policy"]["live_execution_required_for_production"] is True
    assert manifest["policy"]["fixture_or_parser_cannot_satisfy_live_goal"] is True
    assert manifest["policy"]["no_install"] is True
    assert manifest["policy"]["no_network"] is True
    assert manifest["policy"]["disagreement_quarantines"] is True

    cases = manifest["cases"]
    kinds = {case["kind"] for case in cases}
    assert REQUIRED_CASE_KINDS <= kinds
    case_ids = {case["case_id"] for case in cases}
    assert REQUIRED_CASE_IDS <= case_ids
    # Live corpus must not rely on canned SZS stdout fixtures.
    for case in cases:
        assert "stdout" not in case or not case.get("stdout"), (
            f"live case {case.get('case_id')} must not ship canned stdout"
        )
        assert case.get("tptp_source"), f"live case {case.get('case_id')} needs TPTP"


# ---------------------------------------------------------------------------
# Live execution against real pinned binaries
# ---------------------------------------------------------------------------


def test_live_tools_usable_when_present(live_receipt: dict[str, Any]) -> None:
    # When Vampire/E are on PATH (this environment), both must be usable.
    if not (live_receipt.get("vampire_usable") and live_receipt.get("eprover_usable")):
        pytest.skip("pinned Vampire/E not available on this host")
    assert live_receipt["live_execution"] is True
    assert live_receipt["vampire_version_match"] is True
    assert live_receipt["eprover_version_match"] is True
    assert live_receipt["vampire_binary_digest"]
    assert live_receipt["eprover_binary_digest"]
    assert len(live_receipt["vampire_binary_digest"]) == 64
    assert len(live_receipt["eprover_binary_digest"]) == 64


def test_each_tool_executes_required_case_kinds(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("production_certified"):
        if not (live_receipt.get("vampire_usable") and live_receipt.get("eprover_usable")):
            pytest.skip("pinned Vampire/E not available on this host")
    cases = live_receipt.get("cases") or []
    by_tool: dict[str, set[str]] = {"vampire": set(), "eprover": set()}
    for case in cases:
        tool_id = case.get("tool_id")
        if tool_id in by_tool and case.get("execution_mode") != "skipped":
            by_tool[tool_id].add(str(case.get("kind")))
    for tool_id, kinds in by_tool.items():
        assert REQUIRED_CASE_KINDS <= kinds, (
            f"{tool_id} missing kinds: {sorted(REQUIRED_CASE_KINDS - kinds)}"
        )


def test_theorem_and_counter_satisfiable_live(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    by_id = {case["case_id"]: case for case in live_receipt.get("cases") or []}
    for tool_id in ("vampire", "eprover"):
        thm = by_id[f"{tool_id}.theorem"]
        csa = by_id[f"{tool_id}.counter_satisfiable"]
        assert thm["status"] == "theorem_candidate"
        assert thm["authority"] == "candidate"
        assert thm["matched"] is True
        assert csa["status"] == "non_theorem_candidate"
        assert csa["matched"] is True
        assert thm["szs_status"] in {"Theorem", "Unsatisfiable"}
        assert csa["szs_status"] in {"CounterSatisfiable", "Satisfiable"}


def test_mutations_never_remain_theorem(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    for case in live_receipt.get("cases") or []:
        if case.get("kind") != "mutation":
            continue
        assert case["matched"] is True
        assert case["status"] not in {"theorem_candidate", "theorem_authority"}
        assert case["authority"] == "candidate"


def test_replay_preserves_source_and_status(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    by_id = {case["case_id"]: case for case in live_receipt.get("cases") or []}
    for tool_id in ("vampire", "eprover"):
        thm = by_id[f"{tool_id}.theorem"]
        replay = by_id[f"{tool_id}.replay"]
        assert thm["source_digest"] == replay["source_digest"]
        assert thm["status"] == replay["status"] == "theorem_candidate"
        assert thm["authority"] == replay["authority"] == "candidate"


def test_malformed_tptp_quarantined(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    for case in live_receipt.get("cases") or []:
        if case.get("kind") != "malformed":
            continue
        assert case["status"] == "quarantined"
        assert case["matched"] is True
        assert case["authority"] == "candidate"


def test_timeout_resource_bounds(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    for case in live_receipt.get("cases") or []:
        if case.get("kind") != "timeout":
            continue
        assert case["status"] == "timeout"
        assert case["matched"] is True
        assert case["timed_out"] is True
        assert case["limits"]["timeout_seconds"] > 0
        assert case["limits"]["network"] is False


def test_disagreement_quarantines(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    disagreement = [
        case
        for case in live_receipt.get("cases") or []
        if case.get("kind") == "disagreement"
    ]
    assert disagreement
    assert all(case["status"] == "quarantined" and case["matched"] for case in disagreement)
    assert live_receipt.get("disagreement_quarantined") is True


def test_proof_object_and_reconstruction(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    by_id = {case["case_id"]: case for case in live_receipt.get("cases") or []}
    for tool_id in ("vampire", "eprover"):
        proof = by_id[f"{tool_id}.proof_object"]
        recon = by_id[f"{tool_id}.reconstruction"]
        assert proof["status"] == "theorem_candidate"
        assert proof["authority"] == "candidate"
        assert proof["proof_object_present"] is True or proof["proof_bound"] is True
        assert proof["reconstruction_status"] == "unreconstructed"
        assert recon["status"] == "theorem_authority"
        assert recon["authority"] == "theorem"
        assert recon["independent_kernel_reconstruction"] is True
        assert recon["reconstruction_status"] == "kernel_reconstructed"


def test_authority_ceiling_without_reconstruction(live_receipt: dict[str, Any], atp_cert) -> None:
    boundary = atp_cert.atp_results_remain_candidates_without_reconstruction()
    assert boundary["boundary_holds"] is True
    assert boundary["results_are_candidates_without_reconstruction"] is True
    assert (
        boundary["sample_without_reconstruction"]["authority"] == "candidate"
    )
    assert boundary["sample_with_reconstruction"]["authority"] == "theorem"

    for case in live_receipt.get("cases") or []:
        if case.get("execution_mode") == "skipped":
            continue
        if case.get("authority") == "theorem":
            assert case.get("independent_kernel_reconstruction") is True
            assert case.get("reconstruction_status") == "kernel_reconstructed"
        else:
            assert case.get("authority") == "candidate"


def test_receipt_binds_required_fields(live_receipt: dict[str, Any]) -> None:
    if not live_receipt.get("live_execution"):
        pytest.skip("live ATP binaries unavailable")
    bindings = live_receipt.get("bindings") or {}
    assert "binaries" in bindings
    assert bindings["binaries"]["vampire"]["binary_digest"]
    assert bindings["binaries"]["eprover"]["binary_digest"]
    assert bindings["bounds"]["network"] is False
    assert bindings["authority"]["ceiling"] == "reconstruction"
    live_cases = bindings.get("live_cases") or []
    assert live_cases
    for entry in live_cases:
        if entry.get("execution_mode") == "skipped":
            continue
        for field in REQUIRED_BINDING_FIELDS:
            assert field in entry, f"missing binding field {field} on {entry.get('case_id')}"
        assert entry["limits"]["network"] is False
        assert entry["limits"]["install"] is False
        assert entry["binary_digest"]
        assert entry["source_digest"]
        assert entry["artifact_digest"]


def test_offline_policy_never_installs(live_receipt: dict[str, Any]) -> None:
    assert live_receipt.get("network_used") is False
    assert live_receipt.get("install_attempted") is False
    assert live_receipt.get("download_attempted") is False
    policy = live_receipt.get("policy") or {}
    assert policy.get("no_install") is True
    assert policy.get("no_download") is True
    assert policy.get("no_network") is True
    assert policy.get("fixture_or_parser_cannot_satisfy_live_goal") is True


def test_production_certified_when_live_suite_passes(live_receipt: dict[str, Any]) -> None:
    if not (live_receipt.get("vampire_usable") and live_receipt.get("eprover_usable")):
        pytest.skip("pinned Vampire/E not available on this host")
    assert live_receipt["production_certified"] is True
    assert live_receipt["promotion_blocked"] is False
    assert live_receipt["live_semantic_corpus_passed"] is True
    assert not live_receipt.get("block_reasons")


def test_fixture_only_cannot_satisfy_live_goal(atp_cert, offline_env) -> None:
    """Parser fixtures alone are not live execution (FVT-G207 conflict policy)."""

    # Offline SZS corpus still works, but live production requires real runs.
    offline = atp_cert.build_certification_receipt(
        repo_root=REPO_ROOT,
        env=offline_env,
    )
    assert offline.get("semantic_corpus_passed") is True

    # Force unavailable tools → live suite must withhold production certification.
    receipt = atp_cert.build_live_semantic_receipt(
        repo_root=REPO_ROOT,
        env=offline_env,
        vampire_executable="/nonexistent/vampire-binary",
        eprover_executable="/nonexistent/eprover-binary",
    )
    assert receipt["production_certified"] is False
    assert receipt["promotion_blocked"] is True
    assert receipt["live_execution"] is False
    assert receipt["policy"]["fixture_or_parser_cannot_satisfy_live_goal"] is True


def test_certify_atp_live_semantics_entry(atp_cert, offline_env) -> None:
    receipt = atp_cert.certify_atp_live_semantics(
        repo_root=REPO_ROOT,
        env=offline_env,
    )
    assert receipt["handler_id"] == "atp_live_semantic_certification@1"
    assert receipt["lane_id"] == "atp"
    assert receipt["interface"] == LIVE_INTERFACE
    assert receipt["goal_id"] == LIVE_GOAL_ID
    assert receipt["task_id"] == LIVE_TASK_ID
    assert "certified" in receipt
    assert "status" in receipt


# ---------------------------------------------------------------------------
# Durable certificate
# ---------------------------------------------------------------------------


def test_live_certificate_schema(live_certificate: dict[str, Any]) -> None:
    assert live_certificate["interface"] == LIVE_INTERFACE
    assert live_certificate["schema_version"] == LIVE_SCHEMA_VERSION
    assert live_certificate["goal_id"] == LIVE_GOAL_ID
    assert live_certificate["task_id"] == LIVE_TASK_ID
    assert live_certificate["locked_vampire_version"] == LOCKED_VAMPIRE_VERSION
    assert live_certificate["locked_eprover_version"] == LOCKED_EPROVER_VERSION
    assert live_certificate["authority_ceiling"] == "reconstruction"
    assert live_certificate["authority_scope"] == "atp_candidate_until_kernel_reconstruction"
    assert live_certificate["results_are_candidates_without_reconstruction"] is True
    assert live_certificate["kernel_reconstruction_required_for_theorem_authority"] is True
    assert live_certificate.get("receipt_digest_sha256")
    assert len(live_certificate["receipt_digest_sha256"]) == 64
    assert LIVE_CERTIFICATE_PATH.is_file()
    # Objective validation repair evidence binding (FVT-071 / FVT-G207).
    repair = live_certificate.get("objective_validation_repair") or {}
    assert repair.get("schema_version") == "objective-validation-repair/v1"
    assert repair.get("goal_id") == LIVE_GOAL_ID
    assert "objective validation repair" in (repair.get("evidence_terms") or [])
    assert live_certificate.get("policy", {}).get("objective_validation_repair") is True


def test_live_certificate_cases_bind_digests(live_certificate: dict[str, Any]) -> None:
    if not live_certificate.get("live_execution"):
        pytest.skip("live ATP binaries unavailable when certificate was written")
    cases = live_certificate.get("cases") or []
    assert cases
    for case in cases:
        if case.get("execution_mode") == "skipped":
            continue
        assert case.get("binary_digest")
        assert case.get("artifact_digest")
        assert case.get("source_digest")
        assert "reconstruction_status" in case
        assert "limits" in case
        # Durable cert stores digest/preview, not full raw stdout dump.
        assert case.get("raw_szs_output_digest")
        assert "raw_szs_output" not in case or not case.get("raw_szs_output")


def test_live_certificate_matches_toolchain_pins() -> None:
    if not LOCK_PATH.is_file():
        pytest.skip("deployment lock not present in this worktree")
    lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    pins = lock.get("managed_pin_versions") or {}
    if "vampire" in pins:
        assert pins["vampire"] == LOCKED_VAMPIRE_VERSION
    if "eprover" in pins:
        assert pins["eprover"] == LOCKED_EPROVER_VERSION


def test_execute_atp_problem_real_theorem(atp_cert, offline_env) -> None:
    vampire = atp_cert.resolve_executable(["vampire"])
    if vampire is None:
        pytest.skip("vampire not on PATH")
    probe = atp_cert.probe_vampire_identity(env=offline_env, executable=vampire)
    if not probe.get("version_match"):
        pytest.skip("vampire pin mismatch")
    result = atp_cert.execute_atp_problem(
        "vampire",
        vampire,
        "fof(ax1, axiom, p).\nfof(goal, conjecture, p).\n",
        timeout_seconds=10.0,
        env=offline_env,
    )
    assert result["timed_out"] is False
    classified = atp_cert.classify_szs_outcome(
        result["stdout"], result["stderr"]
    )
    assert classified["status"] == "theorem_candidate"
    assert classified["authority"] == "candidate"


def test_build_atp_argv_vampire_uses_spaced_time_limit(atp_cert) -> None:
    argv = atp_cert.build_atp_argv(
        "vampire",
        "/usr/bin/vampire",
        "/tmp/problem.p",
        timeout_seconds=5,
    )
    assert "--time_limit" in argv
    # Vampire 5.0.1 rejects --time_limit=N equals form.
    assert not any(part.startswith("--time_limit=") for part in argv)
    assert "szs" in argv


def test_write_live_certificate_does_not_demote_production(
    atp_cert, offline_env, tmp_path
) -> None:
    """Tool-less re-runs must preserve production live certificate digests.

    Objective validation repair: sealed PATH without Vampire/E cannot overwrite
    a prior production-certified live certificate.
    """

    production = atp_cert.build_live_semantic_receipt(
        repo_root=REPO_ROOT,
        env=offline_env,
    )
    if not production.get("production_certified"):
        pytest.skip("pinned Vampire/E not available to seed production certificate")

    target = tmp_path / "formal_verification_atp_live_certificate.json"
    path = atp_cert.write_live_certificate(
        production,
        repo_root=REPO_ROOT,
        path=target,
        env=offline_env,
    )
    assert path == target
    before = json.loads(target.read_text(encoding="utf-8"))
    assert before["production_certified"] is True
    production_digest = before["receipt_digest_sha256"]

    unavailable = atp_cert.build_live_semantic_receipt(
        repo_root=REPO_ROOT,
        env=offline_env,
        vampire_executable="/nonexistent/vampire-binary",
        eprover_executable="/nonexistent/eprover-binary",
    )
    assert unavailable["production_certified"] is False
    assert unavailable["live_execution"] is False

    preserved = atp_cert.write_live_certificate(
        unavailable,
        repo_root=REPO_ROOT,
        path=target,
        env=offline_env,
    )
    assert preserved == target
    after = json.loads(target.read_text(encoding="utf-8"))
    assert after["production_certified"] is True
    assert after["live_execution"] is True
    assert after["receipt_digest_sha256"] == production_digest

    # Explicit force may replace production with unavailable (diagnostic only).
    forced = atp_cert.write_live_certificate(
        unavailable,
        repo_root=REPO_ROOT,
        path=target,
        env=offline_env,
        force=True,
    )
    assert forced == target
    demoted = json.loads(target.read_text(encoding="utf-8"))
    assert demoted["production_certified"] is False


def test_managed_execution_env_prefers_managed_bin(atp_cert, tmp_path) -> None:
    """Approved/managed install roots are searched without ambient PATH."""

    managed_root = tmp_path / "theorem-provers"
    managed_bin = managed_root / "bin"
    managed_bin.mkdir(parents=True)
    # Non-executable placeholder must not resolve; only real X_OK binaries.
    fake = managed_bin / "vampire"
    fake.write_text("#!/bin/sh\necho Vampire 5.0.1\n", encoding="utf-8")
    fake.chmod(0o755)

    env = {
        "PATH": "/usr/bin",
        "IPFS_DATASETS_PY_THEOREM_PROVERS_ROOT": str(managed_root),
        "XDG_DATA_HOME": str(tmp_path / "empty-xdg"),
    }
    resolved = atp_cert.resolve_executable(["vampire"], env=env)
    assert resolved is not None
    assert Path(resolved).resolve() == fake.resolve()

    managed_env = atp_cert.managed_execution_env(env)
    assert str(managed_bin) in managed_env["PATH"].split(os.pathsep)


def test_objective_validation_repair_receipt_binding(live_receipt: dict[str, Any]) -> None:
    """Receipt always binds the objective validation repair evidence term."""

    repair = live_receipt.get("objective_validation_repair") or {}
    assert repair.get("schema_version") == "objective-validation-repair/v1"
    assert repair.get("goal_id") == LIVE_GOAL_ID
    assert repair.get("interface") == LIVE_INTERFACE
    assert "objective validation repair" in (repair.get("evidence_terms") or [])
    assert live_receipt.get("policy", {}).get("objective_validation_repair") is True
    if live_receipt.get("production_certified"):
        assert repair.get("status") == "satisfied"
    elif not live_receipt.get("live_execution"):
        assert repair.get("status") == "withheld_live_tools_unavailable"
