"""Fail-closed merge admission for :mod:`.patch_plan` proposals.

Admission is pure: it does not apply the patch or run a validator.  A caller
must supply an independently produced successful receipt that is bound to the
same plan, patch, and current repository tree.
"""

from __future__ import annotations

import re
import time
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any, Final

from .patch_plan import PatchPlan, PatchPlanValidationError, patch_digest

PATCH_ADMISSION_SCHEMA: Final[str] = "aseh/patch-admission@1"
VALIDATION_RECEIPT_SCHEMA: Final[str] = "aseh/patch-validation-receipt@1"
_DIFF_PATH_RE: Final[re.Pattern[str]] = re.compile(r"^diff --git a/(.+) b/(.+)$")
_SECRET_PATTERNS: Final[tuple[re.Pattern[str], ...]] = (
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\b(?:ghp|github_pat)_[A-Za-z0-9_]{20,}\b"),
    re.compile(r"(?i)\b(?:api[_-]?key|secret|password|token)\b\s*[:=]\s*[\"'][^\"']{8,}"),
)
_GENERATED_PATH_SUFFIXES: Final[tuple[str, ...]] = (".pyc", ".pyo", ".min.js", ".map")
_GENERATED_PATH_PARTS: Final[frozenset[str]] = frozenset({"__pycache__", "dist", "build", "generated"})
_GENERATED_CONTENT: Final[re.Pattern[str]] = re.compile(r"(?i)(@generated|generated by|do not edit)")


class PatchAdmissionError(ValueError):
    """Raised when a receipt cannot be decoded."""


def _safe_path(path: str) -> str:
    if not isinstance(path, str) or not path or "\x00" in path:
        raise PatchAdmissionError("patch path is invalid")
    value = path.replace("\\", "/")
    pure = PurePosixPath(value)
    if pure.is_absolute() or value != pure.as_posix() or ".." in pure.parts:
        raise PatchAdmissionError("patch path escapes the repository")
    return value


def changed_paths(patch_text: str) -> tuple[str, ...]:
    """Extract the distinct paths declared by a conventional unified diff."""

    if not isinstance(patch_text, str) or not patch_text.strip():
        return ()
    paths: list[str] = []
    for line in patch_text.splitlines():
        match = _DIFF_PATH_RE.match(line)
        if not match:
            continue
        for raw in match.groups():
            if raw != "/dev/null":
                path = _safe_path(raw)
                if path not in paths:
                    paths.append(path)
    return tuple(paths)


def _added_lines(patch_text: str) -> tuple[str, ...]:
    return tuple(
        line[1:]
        for line in patch_text.splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )


def _generated_path(path: str) -> bool:
    pure = PurePosixPath(path)
    return path.endswith(_GENERATED_PATH_SUFFIXES) or bool(set(pure.parts) & _GENERATED_PATH_PARTS)


@dataclass(frozen=True)
class ValidationReceipt:
    """Independent, exact-input result of a successful validator invocation."""

    receipt_id: str
    repository_tree: str
    plan_digest: str
    patch_digest: str
    command: str
    passed: bool
    issued_at_epoch_seconds: int
    independent: bool = True

    def __post_init__(self) -> None:
        for name in ("receipt_id", "repository_tree", "plan_digest", "patch_digest", "command"):
            value = getattr(self, name)
            if not isinstance(value, str) or not value.strip() or "\x00" in value:
                raise PatchAdmissionError(f"receipt {name} must be a non-empty string")
        if not isinstance(self.passed, bool) or not isinstance(self.independent, bool):
            raise PatchAdmissionError("receipt passed and independent must be booleans")
        if isinstance(self.issued_at_epoch_seconds, bool) or not isinstance(self.issued_at_epoch_seconds, int) or self.issued_at_epoch_seconds < 0:
            raise PatchAdmissionError("receipt issued_at_epoch_seconds must be a non-negative integer")

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": VALIDATION_RECEIPT_SCHEMA, "receipt_id": self.receipt_id,
            "repository_tree": self.repository_tree, "plan_digest": self.plan_digest,
            "patch_digest": self.patch_digest, "command": self.command, "passed": self.passed,
            "issued_at_epoch_seconds": self.issued_at_epoch_seconds, "independent": self.independent,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "ValidationReceipt":
        expected = {
            "schema", "receipt_id", "repository_tree", "plan_digest", "patch_digest",
            "command", "passed", "issued_at_epoch_seconds", "independent",
        }
        if not isinstance(value, Mapping) or set(value) != expected:
            raise PatchAdmissionError("validation receipt fields are incomplete or unsupported")
        if value["schema"] != VALIDATION_RECEIPT_SCHEMA:
            raise PatchAdmissionError("unsupported validation receipt schema")
        return cls(**{key: value[key] for key in expected if key != "schema"})


@dataclass(frozen=True)
class PatchAdmissionResult:
    accepted: bool
    reason_codes: tuple[str, ...]
    paths: tuple[str, ...]
    plan_digest: str
    patch_digest: str

    @property
    def reason_code(self) -> str:
        return self.reason_codes[0] if self.reason_codes else ""


class PatchAdmission:
    """Validate a closed PatchPlan, patch payload, and independent receipt."""

    def __init__(self, *, maximum_receipt_age_seconds: int = 3600) -> None:
        if (
            isinstance(maximum_receipt_age_seconds, bool)
            or not isinstance(maximum_receipt_age_seconds, int)
            or maximum_receipt_age_seconds < 0
        ):
            raise ValueError("maximum_receipt_age_seconds must be non-negative")
        self.maximum_receipt_age_seconds = maximum_receipt_age_seconds

    def admit(
        self,
        plan: PatchPlan | Mapping[str, Any],
        patch_text: str,
        receipt: ValidationReceipt | Mapping[str, Any] | None,
        *,
        current_tree: str,
        conflicting_paths: Sequence[str] = (),
        now_epoch_seconds: int | None = None,
    ) -> PatchAdmissionResult:
        try:
            typed_plan = plan if isinstance(plan, PatchPlan) else PatchPlan.from_dict(plan)
        except (PatchPlanValidationError, TypeError, KeyError):
            return PatchAdmissionResult(False, ("invalid_plan",), (), "", "")
        reasons: list[str] = []
        digest = patch_digest(patch_text) if isinstance(patch_text, str) else ""
        try:
            paths = changed_paths(patch_text) if isinstance(patch_text, str) else ()
        except PatchAdmissionError:
            paths = ()
            reasons.append("unsafe_patch")
        if not isinstance(patch_text, str) or not patch_text.strip() or not paths:
            reasons.append("empty_patch")
        if digest != typed_plan.patch_digest:
            reasons.append("patch_digest_mismatch")
        if current_tree != typed_plan.base_tree:
            reasons.append("stale_plan")
        if tuple(paths) != tuple(typed_plan.files):
            reasons.append("file_set_mismatch")
        if any(not typed_plan.scope.admits(path) for path in paths):
            reasons.append("out_of_scope")
        if any(_generated_path(path) for path in paths) or any(_GENERATED_CONTENT.search(line) for line in _added_lines(patch_text)):
            reasons.append("generated_artifact")
        if any(pattern.search(line) for line in _added_lines(patch_text) for pattern in _SECRET_PATTERNS):
            reasons.append("secret_detected")
        try:
            conflicts = {_safe_path(path) for path in conflicting_paths}
        except PatchAdmissionError:
            reasons.append("invalid_conflict_set")
            conflicts = set()
        if conflicts.intersection(paths):
            reasons.append("conflict")

        try:
            typed_receipt = receipt if isinstance(receipt, ValidationReceipt) else ValidationReceipt.from_dict(receipt) if receipt is not None else None
        except (PatchAdmissionError, TypeError, KeyError):
            typed_receipt = None
            reasons.append("invalid_receipt")
        if typed_receipt is None:
            reasons.append("missing_receipt")
        else:
            if not typed_receipt.independent:
                reasons.append("self_validation")
            if not typed_receipt.passed:
                reasons.append("validation_failed")
            if typed_receipt.repository_tree != current_tree:
                reasons.append("stale_receipt")
            if typed_receipt.plan_digest != typed_plan.digest or typed_receipt.patch_digest != digest:
                reasons.append("receipt_binding_mismatch")
            now = int(time.time()) if now_epoch_seconds is None else now_epoch_seconds
            if isinstance(now, bool) or not isinstance(now, int):
                reasons.append("invalid_clock")
            elif (
                typed_receipt.issued_at_epoch_seconds > now
                or now - typed_receipt.issued_at_epoch_seconds > self.maximum_receipt_age_seconds
            ):
                reasons.append("stale_receipt")
        unique_reasons = tuple(dict.fromkeys(reasons))
        return PatchAdmissionResult(not unique_reasons, unique_reasons, paths, typed_plan.digest, digest)


def admit_patch(
    plan: PatchPlan | Mapping[str, Any], patch_text: str,
    receipt: ValidationReceipt | Mapping[str, Any] | None, **kwargs: Any,
) -> PatchAdmissionResult:
    """Convenience entry point for one pure fail-closed admission decision."""

    return PatchAdmission().admit(plan, patch_text, receipt, **kwargs)
