"""Fail-closed admission for a :class:`PatchPlan`.

Admission is intentionally pure: it returns a durable decision object and
does not apply, merge, or promote a patch.  Callers must supply observed tree
and validation evidence rather than trusting a candidate's assertions.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from enum import Enum
from typing import Any

from .patch_plan import PatchPlan, PatchPlanValidationError, SHA256_RE, normalize_path, path_within_scope, sha256_digest


MAX_PATCH_BYTES = 2_000_000
MAX_SINGLE_FILE_BYTES = 1_048_576


class PatchAdmissionReason(str, Enum):
    ADMITTED = "admitted"
    EMPTY_PATCH = "empty_patch"
    PATCH_DIGEST_MISMATCH = "patch_digest_mismatch"
    PATCH_BUDGET_EXCEEDED = "patch_budget_exceeded"
    SINGLE_FILE_BUDGET_EXCEEDED = "single_file_budget_exceeded"
    STALE_PLAN = "stale_plan"
    FILE_SET_MISMATCH = "file_set_mismatch"
    SCOPE_ESCAPE = "scope_escape"
    GENERATED_ARTIFACT = "generated_artifact"
    SECRET_DETECTED = "secret_detected"
    CONFLICT = "conflict"
    MISSING_VALIDATION_RECEIPT = "missing_validation_receipt"
    FAILED_VALIDATION = "failed_validation"
    STALE_VALIDATION_RECEIPT = "stale_validation_receipt"
    MISSING_CURRENT_CANDIDATE_TREE = "missing_current_candidate_tree"
    SELF_VALIDATION = "self_validation"
    INVALID_PLAN = "invalid_plan"


_DIFF_GIT_RE = re.compile(r"^diff --git a/(.+?) b/(.+?)$")
_DIFF_PATH_RE = re.compile(r"^(?:\+\+\+|---) (?:[ab]/)?(.+)$")
_GENERATED_PATH = re.compile(r"(?:^|/)(?:__pycache__|node_modules|dist|build|\.pytest_cache|htmlcov)(?:/|$)|(?:\.py[co]|\.egg-info(?:/|$))")
_GENERATED_MARKER = re.compile(r"(?:do not edit|auto[- ]generated|generated by)", re.IGNORECASE)
_SECRET = re.compile(
    r"(?:-----BEGIN (?:[A-Z ]+ )?PRIVATE KEY-----|"
    r"(?:aws|api|secret|access)[_-]?(?:key|token|secret)?\s*[:=]\s*['\"]?[A-Za-z0-9/+_=-]{16,}|"
    r"(?:gh[pousr]_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9_-]{16,})|"
    r"AKIA[0-9A-Z]{16})",
    re.IGNORECASE,
)


def patch_paths(patch: bytes | str) -> tuple[str, ...]:
    """Extract the repository paths changed by a unified Git diff."""
    text = patch.decode("utf-8", "replace") if isinstance(patch, bytes) else patch
    paths: set[str] = set()
    for line in text.splitlines():
        match = _DIFF_GIT_RE.match(line)
        if match:
            for raw in match.groups():
                if raw != "/dev/null":
                    paths.add(normalize_path(raw))
            continue
        match = _DIFF_PATH_RE.match(line)
        if match and match.group(1) != "/dev/null":
            paths.add(normalize_path(match.group(1)))
    return tuple(sorted(paths))


def _added_lines(patch: bytes | str) -> tuple[str, ...]:
    text = patch.decode("utf-8", "replace") if isinstance(patch, bytes) else patch
    return tuple(line[1:] for line in text.splitlines() if line.startswith("+") and not line.startswith("+++"))


def _largest_file_diff_bytes(patch: bytes | str) -> int:
    """Return the greatest changed-byte contribution for one diff file.

    A unified diff is the only candidate body admitted by this API.  For a
    newly created file this is its complete source content; for an update it
    is a conservative lower bound.  The full patch budget covers the latter.
    """
    raw = patch.encode("utf-8") if isinstance(patch, str) else patch
    greatest = current = 0
    for line in raw.splitlines(keepends=True):
        if line.startswith(b"diff --git "):
            greatest = max(greatest, current)
            current = 0
        current += len(line)
    return max(greatest, current)


def _is_nonempty_patch(patch: bytes | str) -> bool:
    return bool(patch_paths(patch) and _added_lines(patch) or any(
        line.startswith("-") and not line.startswith("---")
        for line in (patch.decode("utf-8", "replace") if isinstance(patch, bytes) else patch).splitlines()
    ))


@dataclass(frozen=True, slots=True)
class ValidationReceipt:
    """Independent validation evidence for the exact candidate patch."""

    base_tree_id: str
    candidate_tree_id: str
    plan_digest: str
    patch_digest: str
    passed: bool
    validator_id: str
    validation_command: str
    receipt_id: str

    def __post_init__(self) -> None:
        for field_name in ("base_tree_id", "candidate_tree_id", "plan_digest", "patch_digest", "validator_id", "validation_command", "receipt_id"):
            if not str(getattr(self, field_name) or "").strip():
                raise PatchPlanValidationError(f"ValidationReceipt.{field_name} is required")
        if not SHA256_RE.fullmatch(self.plan_digest) or not SHA256_RE.fullmatch(self.patch_digest):
            raise PatchPlanValidationError("ValidationReceipt digests must be sha256 digests")

    def to_dict(self) -> dict[str, object]:
        return {
            "base_tree_id": self.base_tree_id, "candidate_tree_id": self.candidate_tree_id,
            "plan_digest": self.plan_digest,
            "patch_digest": self.patch_digest, "passed": self.passed,
            "validator_id": self.validator_id, "validation_command": self.validation_command,
            "receipt_id": self.receipt_id,
        }

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "ValidationReceipt":
        return cls(**{key: value.get(key, "") for key in cls.__dataclass_fields__})


@dataclass(frozen=True, slots=True)
class PatchAdmission:
    """The audit-friendly result of evaluating one exact patch."""

    admitted: bool
    reasons: tuple[PatchAdmissionReason, ...]
    plan_digest: str
    observed_patch_digest: str
    changed_paths: tuple[str, ...]

    @property
    def reason_codes(self) -> tuple[str, ...]:
        return tuple(reason.value for reason in self.reasons)

    def to_dict(self) -> dict[str, object]:
        return {
            "admitted": self.admitted, "reasons": list(self.reason_codes),
            "plan_digest": self.plan_digest, "observed_patch_digest": self.observed_patch_digest,
            "changed_paths": list(self.changed_paths),
        }


def admit_patch_plan(
    plan: PatchPlan | Mapping[str, Any],
    patch: bytes | str,
    *,
    current_base_tree_id: str,
    validation_receipt: ValidationReceipt | Mapping[str, Any] | None,
    current_candidate_tree_id: str | None = None,
    conflicting_paths: Iterable[str] = (),
) -> PatchAdmission:
    """Evaluate all merge gates without performing a merge.

    ``current_base_tree_id`` is observed immediately before admission.  A
    receipt must bind the same base tree, exact patch digest, plan digest, and
    observed current candidate tree.  A false, unavailable, or unobserved
    receipt always denies admission.
    """
    raw_patch = patch.encode("utf-8") if isinstance(patch, str) else patch
    observed_digest = sha256_digest(raw_patch)
    try:
        normalized_plan = plan if isinstance(plan, PatchPlan) else PatchPlan.from_dict(plan)
    except (PatchPlanValidationError, TypeError, AttributeError):
        return PatchAdmission(False, (PatchAdmissionReason.INVALID_PLAN,), "", observed_digest, ())

    try:
        changed_paths = patch_paths(raw_patch)
    except PatchPlanValidationError:
        return PatchAdmission(False, (PatchAdmissionReason.SCOPE_ESCAPE,), normalized_plan.plan_digest, observed_digest, ())

    reasons: list[PatchAdmissionReason] = []
    if not _is_nonempty_patch(raw_patch):
        reasons.append(PatchAdmissionReason.EMPTY_PATCH)
    if observed_digest != normalized_plan.patch_digest:
        reasons.append(PatchAdmissionReason.PATCH_DIGEST_MISMATCH)
    if len(raw_patch) > MAX_PATCH_BYTES:
        reasons.append(PatchAdmissionReason.PATCH_BUDGET_EXCEEDED)
    if _largest_file_diff_bytes(raw_patch) > MAX_SINGLE_FILE_BYTES:
        reasons.append(PatchAdmissionReason.SINGLE_FILE_BUDGET_EXCEEDED)
    if normalized_plan.base_tree_id != str(current_base_tree_id or "").strip():
        reasons.append(PatchAdmissionReason.STALE_PLAN)
    declared_paths = tuple(item.path for item in normalized_plan.files)
    if changed_paths != declared_paths:
        reasons.append(PatchAdmissionReason.FILE_SET_MISMATCH)
    if any(not path_within_scope(path, normalized_plan.scope) for path in changed_paths):
        reasons.append(PatchAdmissionReason.SCOPE_ESCAPE)
    if any(_GENERATED_PATH.search(path) for path in changed_paths) or any(_GENERATED_MARKER.search(line) for line in _added_lines(raw_patch)):
        reasons.append(PatchAdmissionReason.GENERATED_ARTIFACT)
    if any(_SECRET.search(line) for line in _added_lines(raw_patch)):
        reasons.append(PatchAdmissionReason.SECRET_DETECTED)
    try:
        conflicts = {normalize_path(path) for path in conflicting_paths}
    except PatchPlanValidationError:
        conflicts = {"<invalid-conflict-path>"}
    if conflicts.intersection(changed_paths):
        reasons.append(PatchAdmissionReason.CONFLICT)
    if not str(current_candidate_tree_id or "").strip():
        reasons.append(PatchAdmissionReason.MISSING_CURRENT_CANDIDATE_TREE)

    if validation_receipt is None:
        reasons.append(PatchAdmissionReason.MISSING_VALIDATION_RECEIPT)
    else:
        try:
            receipt = validation_receipt if isinstance(validation_receipt, ValidationReceipt) else ValidationReceipt.from_dict(validation_receipt)
        except (PatchPlanValidationError, TypeError, AttributeError):
            reasons.append(PatchAdmissionReason.MISSING_VALIDATION_RECEIPT)
        else:
            if not receipt.passed:
                reasons.append(PatchAdmissionReason.FAILED_VALIDATION)
            if (
                receipt.base_tree_id != normalized_plan.base_tree_id
                or receipt.plan_digest != normalized_plan.plan_digest
                or receipt.patch_digest != observed_digest
                or receipt.candidate_tree_id != current_candidate_tree_id
            ):
                reasons.append(PatchAdmissionReason.STALE_VALIDATION_RECEIPT)
            if receipt.validator_id == normalized_plan.proposer_id:
                reasons.append(PatchAdmissionReason.SELF_VALIDATION)

    unique_reasons = tuple(dict.fromkeys(reasons))
    return PatchAdmission(
        admitted=not unique_reasons,
        reasons=unique_reasons or (PatchAdmissionReason.ADMITTED,),
        plan_digest=normalized_plan.plan_digest,
        observed_patch_digest=observed_digest,
        changed_paths=changed_paths,
    )
