"""CLI runtime provider adapters.

Importing this package is side-effect free: it does not discover tools, install
binaries, start processes, or register providers. Call
:func:`create_goose_provider` (or construct :class:`GooseCLIProvider`) only from
explicit resolution paths.
"""

from __future__ import annotations

from .goose import (
    ALLOWED_OUTPUT_FORMATS,
    APPROVAL_MODES,
    DEFAULT_AGENT_MAX_TOOL_REPETITIONS,
    DEFAULT_AGENT_MAX_TURNS,
    DEFAULT_AGENT_TIMEOUT_SECONDS,
    DEFAULT_CHAT_MAX_TOOL_REPETITIONS,
    DEFAULT_CHAT_MAX_TURNS,
    DEFAULT_CHAT_TIMEOUT_SECONDS,
    OUTPUT_FORMAT_JSON,
    OUTPUT_FORMAT_STREAM_JSON,
    OUTPUT_FORMAT_TEXT,
    PINNED_GOOSE_VERSION,
    PROVIDER_ALIASES,
    PROVIDER_NAME,
    REQUIRED_CHAT_SAFETY_FLAGS,
    GooseAgentPolicy,
    GooseCLIProvider,
    GooseCommandPlan,
    GooseErrorKind,
    GooseParsedOutput,
    GooseProviderError,
    GooseVersionCapabilities,
    build_goose_command,
    build_goose_process_env,
    capabilities_for_version,
    capabilities_from_help,
    classify_goose_failure,
    create_goose_provider,
    goose_error_code,
    goose_provider_spec,
    make_goose_error,
    parse_goose_json,
    parse_goose_output,
    parse_goose_stream_json,
    parse_version_tuple,
)

__all__ = [
    "ALLOWED_OUTPUT_FORMATS",
    "APPROVAL_MODES",
    "DEFAULT_AGENT_MAX_TOOL_REPETITIONS",
    "DEFAULT_AGENT_MAX_TURNS",
    "DEFAULT_AGENT_TIMEOUT_SECONDS",
    "DEFAULT_CHAT_MAX_TOOL_REPETITIONS",
    "DEFAULT_CHAT_MAX_TURNS",
    "DEFAULT_CHAT_TIMEOUT_SECONDS",
    "OUTPUT_FORMAT_JSON",
    "OUTPUT_FORMAT_STREAM_JSON",
    "OUTPUT_FORMAT_TEXT",
    "PINNED_GOOSE_VERSION",
    "PROVIDER_ALIASES",
    "PROVIDER_NAME",
    "REQUIRED_CHAT_SAFETY_FLAGS",
    "GooseAgentPolicy",
    "GooseCLIProvider",
    "GooseCommandPlan",
    "GooseErrorKind",
    "GooseParsedOutput",
    "GooseProviderError",
    "GooseVersionCapabilities",
    "build_goose_command",
    "build_goose_process_env",
    "capabilities_for_version",
    "capabilities_from_help",
    "classify_goose_failure",
    "create_goose_provider",
    "goose_error_code",
    "goose_provider_spec",
    "make_goose_error",
    "parse_goose_json",
    "parse_goose_output",
    "parse_goose_stream_json",
    "parse_version_tuple",
]
