"""CLI runtime provider adapters.

Importing this package is side-effect free: it does not discover tools, install
binaries, start processes, or register providers. Call
:func:`create_goose_provider` / :func:`create_muse_provider` (or construct
:class:`GooseCLIProvider` / :class:`MuseCLIProvider`) only from explicit
resolution paths.
"""

from __future__ import annotations

from .goose import (
    ALLOWED_OUTPUT_FORMATS,
    APPROVAL_MODES,
    DEFAULT_AGENT_MAX_TOOL_REPETITIONS,
    DEFAULT_AGENT_MAX_TURNS,
    DEFAULT_AGENT_TIMEOUT_SECONDS,
    DEFAULT_CHAT_MAX_TOOL_REPETITIONS,
    DEFAULT_CHAT_MAX_TURNS,
    DEFAULT_CHAT_TIMEOUT_SECONDS,
    OUTPUT_FORMAT_JSON,
    OUTPUT_FORMAT_STREAM_JSON,
    OUTPUT_FORMAT_TEXT,
    PINNED_GOOSE_VERSION,
    PROVIDER_ALIASES,
    PROVIDER_NAME,
    REQUIRED_CHAT_SAFETY_FLAGS,
    GooseAgentPolicy,
    GooseCLIProvider,
    GooseCommandPlan,
    GooseErrorKind,
    GooseParsedOutput,
    GooseProviderError,
    GooseVersionCapabilities,
    build_goose_command,
    build_goose_process_env,
    capabilities_for_version,
    capabilities_from_help,
    classify_goose_failure,
    create_goose_provider,
    goose_error_code,
    goose_provider_spec,
    make_goose_error,
    parse_goose_json,
    parse_goose_output,
    parse_goose_stream_json,
    parse_version_tuple,
)
from .muse import (
    APPROVAL_MODES as MUSE_APPROVAL_MODES,
    DEFAULT_AGENT_MAX_MODEL_STEPS,
    DEFAULT_AGENT_TIMEOUT_SECONDS as MUSE_DEFAULT_AGENT_TIMEOUT_SECONDS,
    DEFAULT_CHAT_MAX_MODEL_STEPS,
    DEFAULT_CHAT_TIMEOUT_SECONDS as MUSE_DEFAULT_CHAT_TIMEOUT_SECONDS,
    DEFAULT_MODEL as MUSE_DEFAULT_MODEL,
    PROVIDER_ALIASES as MUSE_PROVIDER_ALIASES,
    PROVIDER_NAME as MUSE_PROVIDER_NAME,
    REASONING_EFFORTS,
    MuseCLIProvider,
    MuseCommandPlan,
    MuseErrorKind,
    MuseParsedOutput,
    MuseProviderError,
    build_muse_exec_argv,
    build_muse_process_env,
    classify_muse_failure,
    create_muse_provider,
    make_muse_error,
    muse_error_code,
    muse_provider_spec,
    parse_muse_jsonl,
)

__all__ = [
    "ALLOWED_OUTPUT_FORMATS",
    "APPROVAL_MODES",
    "DEFAULT_AGENT_MAX_TOOL_REPETITIONS",
    "DEFAULT_AGENT_MAX_TURNS",
    "DEFAULT_AGENT_TIMEOUT_SECONDS",
    "DEFAULT_CHAT_MAX_TOOL_REPETITIONS",
    "DEFAULT_CHAT_MAX_TURNS",
    "DEFAULT_CHAT_TIMEOUT_SECONDS",
    "OUTPUT_FORMAT_JSON",
    "OUTPUT_FORMAT_STREAM_JSON",
    "OUTPUT_FORMAT_TEXT",
    "PINNED_GOOSE_VERSION",
    "PROVIDER_ALIASES",
    "PROVIDER_NAME",
    "REQUIRED_CHAT_SAFETY_FLAGS",
    "GooseAgentPolicy",
    "GooseCLIProvider",
    "GooseCommandPlan",
    "GooseErrorKind",
    "GooseParsedOutput",
    "GooseProviderError",
    "GooseVersionCapabilities",
    "build_goose_command",
    "build_goose_process_env",
    "capabilities_for_version",
    "capabilities_from_help",
    "classify_goose_failure",
    "create_goose_provider",
    "goose_error_code",
    "goose_provider_spec",
    "make_goose_error",
    "parse_goose_json",
    "parse_goose_output",
    "parse_goose_stream_json",
    "parse_version_tuple",
    "DEFAULT_AGENT_MAX_MODEL_STEPS",
    "DEFAULT_CHAT_MAX_MODEL_STEPS",
    "MUSE_APPROVAL_MODES",
    "MUSE_DEFAULT_AGENT_TIMEOUT_SECONDS",
    "MUSE_DEFAULT_CHAT_TIMEOUT_SECONDS",
    "MUSE_DEFAULT_MODEL",
    "MUSE_PROVIDER_ALIASES",
    "MUSE_PROVIDER_NAME",
    "REASONING_EFFORTS",
    "MuseCLIProvider",
    "MuseCommandPlan",
    "MuseErrorKind",
    "MuseParsedOutput",
    "MuseProviderError",
    "build_muse_exec_argv",
    "build_muse_process_env",
    "classify_muse_failure",
    "create_muse_provider",
    "make_muse_error",
    "muse_error_code",
    "muse_provider_spec",
    "parse_muse_jsonl",
]
