"""Shared CLI runtime contracts, errors, and lazy provider registry.

Importing this package is side-effect free: it does not load optional providers,
install tools, start processes, or probe the network. Provider factories are
invoked only through explicit registry ``create`` / ``get_provider`` calls.
"""

from __future__ import annotations

from .contracts import (
    CONTRACT_SCHEMA,
    CONTRACT_VERSION,
    MAX_ALIAS_COUNT,
    MAX_EVENT_COUNT,
    MAX_METADATA_BYTES,
    MAX_PROMPT_CHARS,
    MAX_SERIALIZED_BYTES,
    MAX_TEXT_CHARS,
    CLICapabilities,
    CLIEvent,
    CLIRequest,
    CLIResult,
    CapabilitySupport,
    EventConsumer,
    EventKind,
    ExecutionMode,
    LLMProvider,
    ProviderFactory,
    ProviderSpec,
    RichCLIProvider,
    StreamingCLIProvider,
    adapt_string_provider,
    canonical_json,
    canonical_json_bytes,
    result_text,
)
from .errors import (
    BoundsExceededError,
    CLIErrorRecord,
    CLIRuntimeError,
    CLIRuntimeErrorCode,
    ContractValidationError,
    InvalidStateError,
    MalformedOutputError,
    NonzeroExitError,
    PolicyDeniedError,
    ProcessCancelledError,
    ProcessSpawnError,
    ProcessTimeoutError,
    ProviderLoadError,
    ProviderNotFoundError,
    RegistryCollisionError,
    RegistryError,
)
from .registry import (
    CLIProviderRegistry,
    RegistryEntry,
    get_default_registry,
    get_provider,
    list_providers,
    register_provider,
    reset_default_registry,
    resolve_provider_name,
)

__all__ = [
    "CONTRACT_SCHEMA",
    "CONTRACT_VERSION",
    "MAX_ALIAS_COUNT",
    "MAX_EVENT_COUNT",
    "MAX_METADATA_BYTES",
    "MAX_PROMPT_CHARS",
    "MAX_SERIALIZED_BYTES",
    "MAX_TEXT_CHARS",
    "BoundsExceededError",
    "CLICapabilities",
    "CLIErrorRecord",
    "CLIEvent",
    "CLIProviderRegistry",
    "CLIRequest",
    "CLIResult",
    "CLIRuntimeError",
    "CLIRuntimeErrorCode",
    "CapabilitySupport",
    "ContractValidationError",
    "EventConsumer",
    "EventKind",
    "ExecutionMode",
    "InvalidStateError",
    "LLMProvider",
    "MalformedOutputError",
    "NonzeroExitError",
    "PolicyDeniedError",
    "ProcessCancelledError",
    "ProcessSpawnError",
    "ProcessTimeoutError",
    "ProviderFactory",
    "ProviderLoadError",
    "ProviderNotFoundError",
    "ProviderSpec",
    "RegistryCollisionError",
    "RegistryEntry",
    "RegistryError",
    "RichCLIProvider",
    "StreamingCLIProvider",
    "adapt_string_provider",
    "canonical_json",
    "canonical_json_bytes",
    "get_default_registry",
    "get_provider",
    "list_providers",
    "register_provider",
    "reset_default_registry",
    "resolve_provider_name",
    "result_text",
]
