"""Regressions for bounded retry-repair unstalling.

These tests keep recovery authority deliberately narrow:

* an exhausted generated repair may be rearmed once for each new, persisted
  recovery-policy revision, without rearming or unblocking its source task;
  and
* a validation repair generated from a typed proposal-gate failure retains
  the source task's executable validation contract instead of replacing it
  with a discovery-file existence check.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from ipfs_accelerate_py.agent_supervisor.objectives.backlog_refinery import (
    safe_retry_validation_command,
    validation_retry_task_block,
)
from ipfs_accelerate_py.agent_supervisor.todo_daemon import (
    implementation_daemon as daemon_module,
)
from ipfs_accelerate_py.agent_supervisor.todo_daemon.implementation_daemon import (
    PortalImplementationDaemon,
    PortalTask,
    PortalTaskState,
    parse_task_file,
    retry_budget_repair_runtime_revision,
)

TASK_PREFIX = "## TEST-"
RECOVERY_REVISION = "nested-submodule-output-routing-v1"
NEXT_RECOVERY_REVISION = "nested-submodule-output-routing-v2"


def _recovery_source_tree(root: Path, *, marker: str) -> None:
    source_paths = (
        "todo_daemon/implementation_daemon.py",
        "objectives/backlog_refinery.py",
        "validation/proposal_validation.py",
        "validation/implementation_auto_rescue.py",
        "task_sources/persistent_task_queue.py",
    )
    for relative in source_paths:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"{relative}:{marker}\n", encoding="utf-8")


def _source_and_repair_board(path: Path) -> None:
    path.write_text(
        """# Tasks

## TEST-001 Implement the source contract

- Status: todo
- Completion: auto
- Priority: P0
- Track: contracts
- Outputs: child/src/contract.py
- Validation: cd child && python -m pytest -q tests/test_contract.py
- Acceptance: Implement and validate the source contract.

## TEST-002 Resolve validation retry-budget failure for TEST-001

- Status: todo
- Completion: manual
- Priority: P1
- Track: ops
- Outputs: child/src/contract.py
- Validation: cd child && python -m pytest -q tests/test_contract.py
- Generated by: ipfs_accelerate_py.agent_supervisor.retry-budget-repair@1
- Retry repair source: TEST-001
- Retry failure kind: validation
- Canonical board task: false
- Acceptance: Use the durable failure evidence, then release TEST-001 from strategy blocked_tasks.
""",
        encoding="utf-8",
    )


def _daemon(repo: Path, todo_path: Path) -> PortalImplementationDaemon:
    state_dir = repo / "state"
    return PortalImplementationDaemon(
        todo_path=todo_path,
        state_path=state_dir / "task_state.json",
        strategy_path=state_dir / "strategy.json",
        events_path=state_dir / "events.jsonl",
        repo_root=repo,
        task_header_prefix=TASK_PREFIX,
        max_task_attempts=1,
        worktree_pool_enabled=False,
    )


def _record_recoverable_repair_failure(
    events_path: Path,
    *,
    repair_task: PortalTask,
) -> None:
    events_path.parent.mkdir(parents=True, exist_ok=True)
    events_path.write_text(
        json.dumps(
            {
                "type": "implementation_finished",
                "task_id": repair_task.task_id,
                "canonical_task_cid": repair_task.canonical_task_cid,
                "attempt": 1,
                "returncode": 2,
                "validation_result": {
                    "attempted": True,
                    "passed": False,
                    "reason": "proposal_gate_failed",
                    "error": "proposal_validation_failed",
                    "finding_codes": [
                        "expected_output_force_add_forbidden"
                    ],
                    "failure_review": {
                        "decision": "guide_rescue",
                        "reason_codes": ["proposal_gate_failed"],
                        "finding_codes": [
                            "expected_output_force_add_forbidden"
                        ],
                    },
                },
                "merge_result": {
                    "attempted": False,
                    "merged": False,
                    "reason": "not_attempted",
                },
            },
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def test_recovery_revision_changes_with_relevant_runtime_source(
    tmp_path: Path,
) -> None:
    """A later supervisor fix automatically earns a distinct bounded receipt."""

    root = tmp_path / "agent_supervisor"
    _recovery_source_tree(root, marker="before")
    before = retry_budget_repair_runtime_revision(root)

    (root / "validation" / "proposal_validation.py").write_text(
        "proposal-validation:after\n",
        encoding="utf-8",
    )
    after = retry_budget_repair_runtime_revision(root)

    assert before.startswith("sha256:")
    assert after.startswith("sha256:")
    assert before != after


def test_recovery_revision_reads_deleted_memfd_members_through_loader(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The default revision never resolves a sealed archive's dead pathname."""

    prefix = "/memfd:ipfs-accelerate-lgcvf-live-capsule (deleted)/"
    own_relative = daemon_module._IMPLEMENTATION_DAEMON_CONTROL_PLANE_RELATIVE_PATH
    payloads = {
        prefix + "ipfs_accelerate_py/agent_supervisor/" + relative: (
            f"sealed:{relative}\n".encode()
        )
        for relative in daemon_module.RETRY_BUDGET_REPAIR_RECOVERY_SOURCE_PATHS
    }
    observed: list[str] = []

    class DeletedMemfdLoader:
        def get_data(self, path: str) -> bytes:
            observed.append(path)
            return payloads[path]

    specification = SimpleNamespace(
        origin=prefix + own_relative,
        loader=DeletedMemfdLoader(),
    )
    monkeypatch.setattr(daemon_module, "__spec__", specification)
    monkeypatch.setattr(
        daemon_module,
        "__file__",
        prefix + own_relative,
    )

    revision = retry_budget_repair_runtime_revision()
    digest = hashlib.sha256()
    digest.update(
        daemon_module.RETRY_BUDGET_REPAIR_REARM_POLICY_REVISION.encode("utf-8")
    )
    digest.update(b"\0")
    for relative in daemon_module.RETRY_BUDGET_REPAIR_RECOVERY_SOURCE_PATHS:
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(
            payloads[
                prefix
                + "ipfs_accelerate_py/agent_supervisor/"
                + relative
            ]
        )
        digest.update(b"\0")

    assert revision == "sha256:" + digest.hexdigest()
    assert observed == list(payloads)


def test_import_generation_binding_rejects_loader_byte_drift(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Every protected source must equal the immutable imported archive."""

    capsule_root = tmp_path / "capsule"
    sources = {
        "ipfs_accelerate_py/llm_router.py": b"router-generation\n",
        "ipfs_accelerate_py/agent_supervisor/runtime/grok_cli_runner.py": (
            b"runner-generation\n"
        ),
    }
    for relative, raw in sources.items():
        path = capsule_root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)
    capsule_id = "sha256:" + "c" * 64
    source_head = "a" * 40
    source_tree = "b" * 40
    manifest = {
        "schema": "ipfs_accelerate_py.agent_supervisor."
        "materialized-control-plane@1",
        "source_head": source_head,
        "source_tree": source_tree,
        "files": {
            relative: "sha256:" + hashlib.sha256(raw).hexdigest()
            for relative, raw in sources.items()
        },
        "capsule_id": capsule_id,
    }
    capsule_root.joinpath(
        daemon_module._CONTROL_PLANE_MATERIALIZED_MANIFEST_FILENAME
    ).write_text(json.dumps(manifest), encoding="utf-8")
    pin = SimpleNamespace(
        runner_path=str(
            capsule_root
            / "ipfs_accelerate_py/agent_supervisor/runtime/grok_cli_runner.py"
        ),
        capsule_root=str(capsule_root),
        capsule_id=capsule_id,
        source_head=source_head,
        source_tree=source_tree,
    )
    monkeypatch.setattr(
        daemon_module,
        "build_agent_implementation_control_plane_pin",
        lambda **_kwargs: pin,
    )
    imported = dict(sources)
    monkeypatch.setattr(
        daemon_module,
        "_import_loader_control_plane_source_bytes",
        lambda relative: imported[relative],
    )

    daemon_module._verify_import_loader_control_plane_generation(pin)
    imported["ipfs_accelerate_py/llm_router.py"] = b"other-generation\n"

    with pytest.raises(
        ValueError,
        match="differs from imported loader generation",
    ):
        daemon_module._verify_import_loader_control_plane_generation(pin)


def test_import_loader_generation_binds_sealed_manifest_head_and_tree(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Archive provenance is not reduced to source-tree byte equality."""

    source_head = "a" * 40
    source_tree = "b" * 40
    implementation_raw = b"sealed implementation generation\n"
    implementation_relative = (
        daemon_module._IMPLEMENTATION_DAEMON_CONTROL_PLANE_RELATIVE_PATH
    )
    manifest_filename, schema, _maximum_bytes = (
        daemon_module._CONTROL_PLANE_IMPORTED_GENERATION_MANIFESTS[1]
    )
    manifest = json.dumps(
        {
            "schema": schema,
            "capsule_id": "sha256:" + "c" * 64,
            "source_head": source_head,
            "source_tree": source_tree,
            "files": {
                implementation_relative: (
                    "sha256:"
                    + hashlib.sha256(implementation_raw).hexdigest()
                )
            },
        }
    ).encode()
    members = {
        manifest_filename: manifest,
        implementation_relative: implementation_raw,
    }

    def loader_bytes(relative: str, **_kwargs: object) -> bytes:
        try:
            return members[relative]
        except KeyError as exc:
            raise OSError("archive member absent") from exc

    monkeypatch.setattr(
        daemon_module,
        "_import_loader_control_plane_source_bytes",
        loader_bytes,
    )

    assert daemon_module._import_loader_control_plane_source_generation() == (
        source_head,
        source_tree,
    )
    members[implementation_relative] = b"substituted implementation generation\n"

    with pytest.raises(ValueError, match="generation manifest is invalid"):
        daemon_module._import_loader_control_plane_source_generation()


def test_materializer_subprocess_environment_drops_inherited_secrets(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Provider and Quack credentials never enter the verifier process."""

    sentinel = "sentinel-provider-quack-token-secret"
    monkeypatch.setenv("OPENAI_API_KEY", sentinel)
    monkeypatch.setenv("QUACK_ENDPOINT_SECRET", sentinel)
    monkeypatch.setenv("ASREF_SENTINEL_SECRET", sentinel)
    source_root = tmp_path / "repo"
    source_root.mkdir()
    capsule_parent = tmp_path / "capsules"
    source_head = "a" * 40
    source_tree = "b" * 40
    capsule_id = "sha256:" + "c" * 64
    capsule_root = capsule_parent / capsule_id.removeprefix("sha256:")
    runner_path = (
        capsule_root
        / "ipfs_accelerate_py/agent_supervisor/runtime/grok_cli_runner.py"
    )
    receipt = {
        "schema": (
            "ipfs_accelerate_py.agent_supervisor.accepted-control-plane@2"
        ),
        "runner_path": str(runner_path),
        "runner_sha256": "sha256:" + "d" * 64,
        "capsule_root": str(capsule_root),
        "capsule_id": capsule_id,
        "source_head": source_head,
        "source_tree": source_tree,
        "archive_sha256": "sha256:" + "e" * 64,
    }
    pin = SimpleNamespace(
        source_head=source_head,
        source_tree=source_tree,
        as_dict=lambda: receipt,
    )
    observed: dict[str, object] = {}

    def fake_run(*_args: object, **kwargs: object) -> object:
        observed.update(kwargs)
        return SimpleNamespace(
            returncode=0,
            stdout=json.dumps(receipt),
            stderr="",
        )

    monkeypatch.setattr(daemon_module.subprocess, "run", fake_run)
    monkeypatch.setattr(
        daemon_module,
        "build_agent_implementation_control_plane_pin",
        lambda **_kwargs: pin,
    )

    materialized = daemon_module._materialize_imported_control_plane_capsule(
        source_root=source_root,
        capsule_parent=capsule_parent,
        source_head=source_head,
        source_tree=source_tree,
    )

    child_environment = observed["env"]
    assert materialized is pin
    assert isinstance(child_environment, dict)
    assert set(child_environment) == {"LANG", "LC_ALL", "PATH"}
    assert sentinel not in child_environment
    assert sentinel not in child_environment.values()
    assert "OPENAI_API_KEY" not in child_environment
    assert "QUACK_ENDPOINT_SECRET" not in child_environment


def test_import_generation_capture_uses_verified_repo_root_not_module_path(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """A deleted module origin cannot choose or prevent the source root."""

    source_root = tmp_path / "repo"
    source_root.mkdir()
    capsule_parent = tmp_path / "capsules"
    capsule_parent.mkdir()
    head = "a" * 40
    tree = "b" * 40
    pin = SimpleNamespace(source_head=head, source_tree=tree)
    launch = object()
    calls: list[object] = []

    def generation(root: Path) -> tuple[str, str]:
        calls.append(("generation", Path(root)))
        return head, tree

    def materialize(**kwargs: object) -> object:
        calls.append(("materialize", kwargs))
        return pin

    monkeypatch.setattr(daemon_module, "REPO_ROOT", source_root)
    monkeypatch.setattr(
        daemon_module,
        "__file__",
        "/memfd:ipfs-accelerate-lgcvf-live-capsule (deleted)/"
        "ipfs_accelerate_py/agent_supervisor/todo_daemon/implementation_daemon.py",
    )
    monkeypatch.setattr(
        daemon_module,
        "agent_implementation_control_plane_source_generation",
        generation,
    )
    monkeypatch.setattr(
        daemon_module,
        "_import_loader_control_plane_source_generation",
        lambda: calls.append(("imported_generation",)) or (head, tree),
    )
    monkeypatch.setattr(
        daemon_module,
        "_materialize_imported_control_plane_capsule",
        materialize,
    )
    monkeypatch.setattr(
        daemon_module,
        "_verify_import_loader_control_plane_generation",
        lambda observed_pin: calls.append(("verify", observed_pin)),
    )
    monkeypatch.setattr(
        daemon_module,
        "seal_agent_implementation_control_plane_capsule",
        lambda observed_pin: calls.append(("seal", observed_pin)) or launch,
    )
    monkeypatch.setattr(
        daemon_module.tempfile,
        "mkdtemp",
        lambda **_kwargs: str(capsule_parent),
    )

    captured = daemon_module._capture_imported_control_plane_generation()

    assert captured == (pin, launch, capsule_parent)
    assert calls == [
        ("generation", source_root),
        ("imported_generation",),
        (
            "materialize",
            {
                "source_root": source_root,
                "capsule_parent": capsule_parent,
                "source_head": head,
                "source_tree": tree,
            },
        ),
        ("verify", pin),
        ("generation", source_root),
        ("seal", pin),
    ]


def test_import_generation_capture_rejects_a_different_sealed_head(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """An identical tree from a different commit cannot replace provenance."""

    source_root = tmp_path / "repo"
    source_root.mkdir()
    head = "a" * 40
    tree = "b" * 40
    monkeypatch.setattr(daemon_module, "REPO_ROOT", source_root)
    monkeypatch.setattr(
        daemon_module,
        "agent_implementation_control_plane_source_generation",
        lambda _root: (head, tree),
    )
    monkeypatch.setattr(
        daemon_module,
        "_import_loader_control_plane_source_generation",
        lambda: ("c" * 40, tree),
    )

    with pytest.raises(
        ValueError,
        match="generation differs from verified source",
    ):
        daemon_module._capture_imported_control_plane_generation()


def test_attempt_limited_retry_repair_rearms_once_per_persisted_fingerprint(
    tmp_path: Path,
) -> None:
    """Each durable policy revision grants exactly one repair-only retry."""

    repo = tmp_path / "repo"
    repo.mkdir()
    todo_path = repo / "tasks.todo.md"
    _source_and_repair_board(todo_path)
    daemon = _daemon(repo, todo_path)
    source, repair = parse_task_file(todo_path, TASK_PREFIX)
    daemon._register_task_identities((source, repair))
    source_identity = daemon._identity_for_task(source)
    repair_identity = daemon._identity_for_task(repair)

    state = PortalTaskState(
        task_identities={
            source.task_id: source_identity.to_dict(),
            repair.task_id: repair_identity.to_dict(),
        },
        implementation_attempts={source.task_id: 1, repair.task_id: 1},
        implementation_attempts_by_cid={
            source_identity.canonical_task_cid: 1,
            repair_identity.canonical_task_cid: 1,
        },
        retry_budget_repair_rearm_receipts={},
    )
    state.save(daemon.state_path)
    strategy_before = {
        "blocked_tasks": [source.task_id, "TEST-999"],
        "retry_budget_findings": [
            {
                "source_task_id": source.task_id,
                "follow_up_task_id": repair.task_id,
                "failure_kind": "validation",
            }
        ],
    }
    daemon.strategy_path.parent.mkdir(parents=True, exist_ok=True)
    daemon.strategy_path.write_text(
        json.dumps(strategy_before, sort_keys=True),
        encoding="utf-8",
    )
    daemon.task_queue.register_task(source_identity).record_failure(
        "validation"
    )
    daemon.task_queue.register_task(repair_identity).record_failure(
        "validation"
    )
    daemon.task_queue.save()
    _record_recoverable_repair_failure(
        daemon.events_path,
        repair_task=repair,
    )

    first = daemon._rearm_attempt_limited_retry_repairs(
        state,
        (source, repair),
        {source.task_id: "blocked", repair.task_id: "ready"},
        recovery_revision=RECOVERY_REVISION,
    )
    persisted = PortalTaskState.load(daemon.state_path)
    persisted_daemon = _daemon(repo, todo_path)

    assert len(first) == 1
    assert first[0]["repair_task_id"] == repair.task_id
    assert first[0]["source_task_id"] == source.task_id
    assert first[0]["recovery_revision"] == RECOVERY_REVISION
    assert first[0]["rearm_fingerprint"]
    assert persisted.retry_budget_repair_rearm_receipts == {
        repair_identity.canonical_task_cid: [
            first[0]["rearm_fingerprint"]
        ]
    }
    assert persisted.implementation_attempts[source.task_id] == 1
    assert persisted.implementation_attempts_by_cid[
        source_identity.canonical_task_cid
    ] == 1
    assert repair.task_id not in persisted.implementation_attempts
    assert (
        repair_identity.canonical_task_cid
        not in persisted.implementation_attempts_by_cid
    )
    assert persisted_daemon.task_queue.is_cooled_down(
        source_identity.canonical_task_cid
    ) is True
    assert persisted_daemon.task_queue.is_cooled_down(
        repair_identity.canonical_task_cid
    ) is False
    assert json.loads(daemon.strategy_path.read_text(encoding="utf-8")) == (
        strategy_before
    )
    assert "- Status: completed" not in todo_path.read_text(encoding="utf-8")

    # Model the single rearmed try failing. The durable receipt must prevent
    # the same policy revision from resetting it after a daemon restart.
    persisted.implementation_attempts[repair.task_id] = 1
    persisted.implementation_attempts_by_cid[
        repair_identity.canonical_task_cid
    ] = 1
    persisted.save(daemon.state_path)
    persisted_daemon.task_queue.register_task(repair_identity).record_failure(
        "validation"
    )
    persisted_daemon.task_queue.save()
    restarted = _daemon(repo, todo_path)
    restarted_state = PortalTaskState.load(restarted.state_path)

    second = restarted._rearm_attempt_limited_retry_repairs(
        restarted_state,
        (source, repair),
        {source.task_id: "blocked", repair.task_id: "ready"},
        recovery_revision=RECOVERY_REVISION,
    )
    still_exhausted = PortalTaskState.load(restarted.state_path)

    assert second == []
    assert still_exhausted.implementation_attempts[repair.task_id] == 1
    assert still_exhausted.implementation_attempts_by_cid[
        repair_identity.canonical_task_cid
    ] == 1
    assert still_exhausted.retry_budget_repair_rearm_receipts == (
        persisted.retry_budget_repair_rearm_receipts
    )
    assert json.loads(restarted.strategy_path.read_text(encoding="utf-8")) == (
        strategy_before
    )
    assert "- Status: completed" not in todo_path.read_text(encoding="utf-8")

    # A deliberately new recovery policy may grant exactly one further try.
    # Its fingerprint is appended instead of replacing the first receipt.
    third = restarted._rearm_attempt_limited_retry_repairs(
        still_exhausted,
        (source, repair),
        {source.task_id: "blocked", repair.task_id: "ready"},
        recovery_revision=NEXT_RECOVERY_REVISION,
    )
    persisted_v2 = PortalTaskState.load(restarted.state_path)
    persisted_v2_daemon = _daemon(repo, todo_path)

    assert len(third) == 1
    assert third[0]["repair_task_id"] == repair.task_id
    assert third[0]["recovery_revision"] == NEXT_RECOVERY_REVISION
    assert third[0]["rearm_fingerprint"] != first[0]["rearm_fingerprint"]
    assert persisted_v2.retry_budget_repair_rearm_receipts == {
        repair_identity.canonical_task_cid: [
            first[0]["rearm_fingerprint"],
            third[0]["rearm_fingerprint"],
        ]
    }
    assert persisted_v2.implementation_attempts[source.task_id] == 1
    assert persisted_v2.implementation_attempts_by_cid[
        source_identity.canonical_task_cid
    ] == 1
    assert repair.task_id not in persisted_v2.implementation_attempts
    assert (
        repair_identity.canonical_task_cid
        not in persisted_v2.implementation_attempts_by_cid
    )
    assert persisted_v2_daemon.task_queue.is_cooled_down(
        source_identity.canonical_task_cid
    ) is True
    assert persisted_v2_daemon.task_queue.is_cooled_down(
        repair_identity.canonical_task_cid
    ) is False

    # Keep all historical fingerprints: returning from revision B to A must
    # not reopen A's already-consumed budget.
    persisted_v2.implementation_attempts[repair.task_id] = 1
    persisted_v2.implementation_attempts_by_cid[
        repair_identity.canonical_task_cid
    ] = 1
    persisted_v2.save(restarted.state_path)
    persisted_v2_daemon.task_queue.register_task(
        repair_identity
    ).record_failure(
        "validation"
    )
    persisted_v2_daemon.task_queue.save()
    returned_to_v1 = _daemon(repo, todo_path)
    returned_state = PortalTaskState.load(returned_to_v1.state_path)

    fourth = returned_to_v1._rearm_attempt_limited_retry_repairs(
        returned_state,
        (source, repair),
        {source.task_id: "blocked", repair.task_id: "ready"},
        recovery_revision=RECOVERY_REVISION,
    )
    final_state = PortalTaskState.load(returned_to_v1.state_path)

    assert fourth == []
    assert final_state.implementation_attempts[repair.task_id] == 1
    assert final_state.implementation_attempts_by_cid[
        repair_identity.canonical_task_cid
    ] == 1
    assert final_state.retry_budget_repair_rearm_receipts == (
        persisted_v2.retry_budget_repair_rearm_receipts
    )
    assert json.loads(
        returned_to_v1.strategy_path.read_text(encoding="utf-8")
    ) == strategy_before
    assert "- Status: completed" not in todo_path.read_text(encoding="utf-8")


def test_daemon_pass_selects_rearmed_repair_and_keeps_source_blocked(
    tmp_path: Path,
) -> None:
    """The live selection path consumes the bounded recovery before filtering."""

    repo = tmp_path / "repo"
    repo.mkdir()
    todo_path = repo / "tasks.todo.md"
    _source_and_repair_board(todo_path)
    daemon = _daemon(repo, todo_path)
    source, repair = daemon._load_tasks()
    daemon._register_task_identities((source, repair))
    source_identity = daemon._identity_for_task(source)
    repair_identity = daemon._identity_for_task(repair)
    PortalTaskState(
        task_identities={
            source.task_id: source_identity.to_dict(),
            repair.task_id: repair_identity.to_dict(),
        },
        implementation_attempts={
            source.task_id: 1,
            repair.task_id: 1,
        },
        implementation_attempts_by_cid={
            source_identity.canonical_task_cid: 1,
            repair_identity.canonical_task_cid: 1,
        },
    ).save(daemon.state_path)
    daemon.strategy_path.parent.mkdir(parents=True, exist_ok=True)
    daemon.strategy_path.write_text(
        json.dumps({"blocked_tasks": [source.task_id]}),
        encoding="utf-8",
    )
    daemon.task_queue.register_task(repair_identity).record_failure(
        "validation"
    )
    daemon.task_queue.save()

    result = daemon.run_once()
    persisted = PortalTaskState.load(daemon.state_path)

    assert result["active_task_id"] == repair.task_id
    assert result["attempt_limited_task_ids"] == []
    assert result["retry_budget_repair_rearms"][0][
        "repair_task_id"
    ] == repair.task_id
    assert persisted.task_statuses[source.task_id] == "blocked"
    assert persisted.task_statuses[repair.task_id] == "ready"
    assert persisted.implementation_attempts[source.task_id] == 1
    assert repair.task_id not in persisted.implementation_attempts
    assert json.loads(daemon.strategy_path.read_text(encoding="utf-8"))[
        "blocked_tasks"
    ] == [source.task_id]


def test_generated_validation_repair_inherits_authoritative_source_validation(
    tmp_path: Path,
) -> None:
    """A typed proposal failure must not reduce validation to discovery."""

    source_validation = (
        "cd ipfs_kit_py && python -m pytest -q "
        "tests/kernel_vfs/contracts/test_host_contracts.py"
    )
    typed_failure = (
        "validation_pre_dispatch:proposal_validation_failed:"
        "proposal_gate_failed"
    )
    discovery_path = tmp_path / "discovery" / "retry-budget.md"
    source = PortalTask(
        task_id="TEST-101",
        title="Define host filesystem contracts",
        status="todo",
        completion="auto",
        priority="P0",
        track="contracts",
        outputs=[
            "ipfs_kit_py/ipfs_kit_py/core/vfs/host_contracts.py",
            "ipfs_kit_py/tests/kernel_vfs/contracts/test_host_contracts.py",
        ],
        validation=[source_validation],
        acceptance="The host contract is executable and fully validated.",
        metadata={"parallel lane": "contracts"},
    )

    selected_validation = safe_retry_validation_command(
        typed_failure,
        discovery_path=discovery_path,
        fallback_commands=source.validation,
    )
    block = validation_retry_task_block(
        task_id="TEST-102",
        source_task=source,
        failed_command=typed_failure,
        discovery_path=discovery_path,
    )
    board_path = tmp_path / "repair.todo.md"
    board_path.write_text(block, encoding="utf-8")
    repair = parse_task_file(board_path, TASK_PREFIX)[0]

    assert selected_validation == source_validation
    assert repair.validation == [source_validation]
    assert repair.outputs == source.outputs
    assert repair.status == "todo"
    assert repair.completion == "manual"
    assert repair.metadata["generated by"] == (
        "ipfs_accelerate_py.agent_supervisor.retry-budget-repair@1"
    )
    assert repair.metadata["retry repair source"] == source.task_id
    assert repair.metadata["retry failure kind"] == "validation"
    assert str(discovery_path) in repair.acceptance
    assert f"test -f {discovery_path}" not in block
    assert "release TEST-101 from strategy blocked_tasks" in repair.acceptance


def test_legacy_discovery_only_repair_inherits_validation_at_load(
    tmp_path: Path,
) -> None:
    """Already-published repair appendices receive the same safe migration."""

    repo = tmp_path / "repo"
    repo.mkdir()
    discovery_path = repo / "state" / "discovery" / "legacy.md"
    todo_path = repo / "tasks.todo.md"
    source_validation = (
        "cd child && python -m pytest -q tests/test_contract.py"
    )
    todo_path.write_text(
        f"""# Tasks

## TEST-201 Implement the source contract

- Status: todo
- Completion: auto
- Priority: P0
- Track: contracts
- Outputs: child/src/contract.py
- Validation: {source_validation}
- Acceptance: Implement and validate the source contract.

## TEST-202 Resolve validation retry-budget failure for TEST-201

- Status: todo
- Completion: manual
- Priority: P1
- Track: ops
- Outputs: child/src/contract.py
- Validation: test -f {discovery_path}
- Generated by: ipfs_accelerate_py.agent_supervisor.retry-budget-repair@1
- Retry repair source: TEST-201
- Retry failure kind: validation
- Retry repair discovery: {discovery_path}
- Canonical board task: false
- Acceptance: Use the durable failure evidence, then release TEST-201 from strategy blocked_tasks.
""",
        encoding="utf-8",
    )
    raw_source, raw_repair = parse_task_file(todo_path, TASK_PREFIX)
    daemon = _daemon(repo, todo_path)

    loaded_source, loaded_repair = daemon._load_tasks()

    assert raw_source.validation == [source_validation]
    assert raw_repair.validation == [f"test -f {discovery_path}"]
    assert loaded_source.validation == [source_validation]
    assert loaded_repair.validation == [source_validation]
    assert loaded_repair.metadata[
        "retry repair validation inherited from"
    ] == loaded_source.task_id
    assert todo_path.read_text(encoding="utf-8").count(
        f"test -f {discovery_path}"
    ) == 1
