"""Hermetic CID wire and accepted control-plane capsule closure tests."""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

from ipfs_accelerate_py import llm_router
from ipfs_accelerate_py.utils import cid_utils

# Independently published multiformats vectors.  These literals must not be
# generated by the implementation under test.
KNOWN_EMPTY_RAW_CID = (
    "bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku"
)
KNOWN_HELLO_WORLD_RAW_CID = (
    "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e"
)
KNOWN_A_1_DAG_JSON_CID = (
    "baguqeeraafnl2724yv5c3wklowipaswybbbhhec64m7mltv6vzrco2ux7bra"
)


def _multibase_for_binary(binary: bytes) -> str:
    """Test-only base32 wrapper for constructing malformed wire inputs."""

    return "b" + base64.b32encode(binary).decode("ascii").lower().rstrip("=")


def _canonical(value: dict[str, Any]) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def _write_capsule(
    root: Path,
    payloads: dict[str, bytes],
) -> llm_router.AgentImplementationControlPlanePin:
    digests: dict[str, str] = {}
    for relative, payload in sorted(payloads.items()):
        path = root / relative
        path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        path.write_bytes(payload)
        path.chmod(0o400)
        digests[relative] = "sha256:" + hashlib.sha256(payload).hexdigest()
    manifest: dict[str, Any] = {
        "schema": llm_router._AGENT_CONTROL_PLANE_MANIFEST_SCHEMA,
        "source_head": "0" * 40,
        "source_tree": "1" * 40,
        "files": dict(sorted(digests.items())),
    }
    manifest["capsule_id"] = llm_router._content_addressed_mapping(
        manifest,
        identity_field="capsule_id",
    )
    manifest_path = root / llm_router._AGENT_CONTROL_PLANE_MANIFEST_FILENAME
    manifest_path.write_bytes(_canonical(manifest) + b"\n")
    manifest_path.chmod(0o400)
    for directory in sorted(
        (path for path in root.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    ):
        directory.chmod(0o500)
    root.chmod(0o500)
    return llm_router.build_agent_implementation_control_plane_pin(
        runner_path=(
            root
            / "ipfs_accelerate_py"
            / "agent_supervisor"
            / "runtime"
            / "grok_cli_runner.py"
        ),
        capsule_root=root,
    )


def _inert_required_payloads() -> dict[str, bytes]:
    return {
        relative: f"# inert accepted dependency: {relative}\n".encode()
        for relative in llm_router._AGENT_CONTROL_PLANE_RELATIVE_FILES
    }


def _full_source_capsule(root: Path) -> llm_router.AgentImplementationControlPlanePin:
    source_root = Path(llm_router.__file__).resolve().parents[1]
    source_files = llm_router._agent_control_plane_source_files(
        source_root,
        verify_loaded_origins=False,
    )
    payloads = {
        str(path.relative_to(source_root)): path.read_bytes() for path in source_files
    }
    return _write_capsule(root, payloads)


def test_dependency_free_known_vectors_and_digest_wrapping() -> None:
    assert cid_utils.cid_for_bytes(b"") == KNOWN_EMPTY_RAW_CID
    assert cid_utils.cid_for_bytes(b"hello world") == KNOWN_HELLO_WORLD_RAW_CID
    assert cid_utils.cid_for_dag_json({"a": 1}) == KNOWN_A_1_DAG_JSON_CID
    assert cid_utils.validate_cid(KNOWN_EMPTY_RAW_CID, codecs=("raw",)) == (
        KNOWN_EMPTY_RAW_CID
    )
    assert cid_utils.validate_cid(
        KNOWN_A_1_DAG_JSON_CID,
        codecs=("dag-json",),
    ) == KNOWN_A_1_DAG_JSON_CID
    digest = hashlib.sha256(b"hello world").digest()
    assert cid_utils.digest_bytes_from_cid(KNOWN_HELLO_WORLD_RAW_CID) == digest
    assert cid_utils.digest_hex_from_cid(KNOWN_HELLO_WORLD_RAW_CID) == digest.hex()
    assert cid_utils.cid_from_sha256_digest(digest) == KNOWN_HELLO_WORLD_RAW_CID


def test_dependency_free_codec_matches_optional_external_library() -> None:
    if importlib.util.find_spec("multiformats") is None:
        pytest.skip("optional multiformats parity oracle is not installed")
    from multiformats import CID, multihash

    vectors = (
        (b"", "raw", KNOWN_EMPTY_RAW_CID),
        (b"hello world", "raw", KNOWN_HELLO_WORLD_RAW_CID),
        (b'{"a":1}', "dag-json", KNOWN_A_1_DAG_JSON_CID),
    )
    for payload, codec, known in vectors:
        external = str(
            CID("base32", 1, codec, multihash.digest(payload, "sha2-256"))
        )
        assert external == known
        assert cid_utils.cid_for_bytes(payload, codec=codec) == external


@pytest.mark.parametrize(
    "malformed",
    [
        # Non-minimal version 1, then otherwise valid raw profile bytes.
        _multibase_for_binary(b"\x81\x00\x55\x12\x20" + bytes(32)),
        # Overflowing and truncated uvarints.
        _multibase_for_binary(b"\x81" * 9 + b"\x02"),
        _multibase_for_binary(b"\x81"),
        # Wrong field ordering: multihash code is parsed as the codec.
        _multibase_for_binary(b"\x01\x12\x55\x20" + bytes(32)),
        # Declared digest sizes that do not match the fixed profile/payload.
        _multibase_for_binary(b"\x01\x55\x12\x1f" + bytes(31)),
        _multibase_for_binary(b"\x01\x55\x12\x20" + bytes(31)),
        # One otherwise valid CID with an unconsumed suffix.
        _multibase_for_binary(b"\x01\x55\x12\x20" + bytes(33)),
    ],
)
def test_wire_decoder_rejects_malformed_varints_order_and_lengths(
    malformed: str,
) -> None:
    with pytest.raises(ValueError):
        cid_utils.validate_cid(malformed)


@pytest.mark.parametrize(
    "malformed",
    [
        KNOWN_EMPTY_RAW_CID.upper(),
        KNOWN_EMPTY_RAW_CID + "=",
        # Same decoded bytes as the known vector, but nonzero unused base32 bits.
        KNOWN_EMPTY_RAW_CID[:-1] + "v",
    ],
)
def test_wire_decoder_rejects_noncanonical_base32(malformed: str) -> None:
    with pytest.raises(ValueError):
        cid_utils.validate_cid(malformed)


def test_dependency_free_surface_rejects_bool_nonbytes_and_repr() -> None:
    with pytest.raises(TypeError):
        cid_utils.cid_for_bytes(True)  # type: ignore[arg-type]
    with pytest.raises(TypeError):
        cid_utils.cid_for_bytes(bytearray(b"x"))  # type: ignore[arg-type]
    with pytest.raises(ValueError):
        cid_utils.cid_for_bytes(b"", version=True)
    with pytest.raises(ValueError):
        cid_utils.validate_cid(KNOWN_EMPTY_RAW_CID, version=True)
    with pytest.raises(TypeError):
        cid_utils.cid_from_sha256_digest(True)  # type: ignore[arg-type]
    with pytest.raises(TypeError, match="not JSON serializable"):
        cid_utils.cid_for_dag_json({"opaque": object()})


def test_reviewed_capsule_manifest_closes_identity_dependencies() -> None:
    dependencies = set(llm_router._AGENT_CONTROL_PLANE_RELATIVE_FILES)
    assert {
        "ipfs_accelerate_py/utils/cid_utils.py",
        "ipfs_accelerate_py/agent_supervisor/core/multiformats_identity.py",
    }.issubset(dependencies)


@pytest.mark.parametrize(
    "missing",
    [
        "ipfs_accelerate_py/utils/cid_utils.py",
        "ipfs_accelerate_py/agent_supervisor/core/multiformats_identity.py",
    ],
)
def test_capsule_missing_identity_dependency_is_denied(
    tmp_path: Path,
    missing: str,
) -> None:
    payloads = _inert_required_payloads()
    payloads.pop(missing)
    with pytest.raises(ValueError, match="missing a dependency"):
        _write_capsule(tmp_path / "missing", payloads)


@pytest.mark.parametrize(
    "substituted",
    [
        "ipfs_accelerate_py/utils/cid_utils.py",
        "ipfs_accelerate_py/agent_supervisor/core/multiformats_identity.py",
    ],
)
def test_capsule_substituted_identity_dependency_is_denied(
    tmp_path: Path,
    substituted: str,
) -> None:
    root = tmp_path / "substituted"
    pin = _write_capsule(root, _inert_required_payloads())
    target = root / substituted
    target.chmod(0o600)
    target.write_bytes(b"# substituted after review\n")
    target.chmod(0o400)
    with pytest.raises(ValueError, match="content drifted"):
        llm_router.build_agent_implementation_control_plane_pin(
            runner_path=pin.runner_path,
            capsule_root=root,
        )


_HERMETIC_IMPORT_BOOTSTRAP = r"""
import importlib
import importlib.machinery
import importlib.util
import json
import sys
import types

archive = sys.argv[1]
sys.path.insert(0, archive)
import ipfs_accelerate_py

name = "ipfs_accelerate_py.agent_supervisor"
package = types.ModuleType(name)
package.__file__ = archive + "/ipfs_accelerate_py/agent_supervisor/__init__.py"
package.__package__ = name
package.__path__ = [archive + "/ipfs_accelerate_py/agent_supervisor"]
package.__spec__ = importlib.machinery.ModuleSpec(name, loader=None, is_package=True)
sys.modules[name] = package
ipfs_accelerate_py.agent_supervisor = package

identity = importlib.import_module(name + ".core.multiformats_identity")
router = importlib.import_module("ipfs_accelerate_py.llm_router")
timeout = importlib.import_module(name + ".todo_daemon.implementation_timeout")
sys.modules[name + ".implementation_timeout"] = timeout
package.implementation_timeout = timeout
targets = [
    name + ".runtime.configured_board_scheduler",
    name + ".runtime.multi_supervisor_runner",
    name + ".todo_daemon.implementation_supervisor",
]
modules = [importlib.import_module(target) for target in targets]
raw = identity.cid_for_bytes(b"")
dag = identity.cid_for_dag_json({"a": 1})
assert identity.validate_cid(raw, codecs=("raw",)) == raw
assert identity.validate_cid(dag, codecs=("dag-json",)) == dag
assert raw == "bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku"
assert dag == "baguqeeraafnl2724yv5c3wklowipaswybbbhhec64m7mltv6vzrco2ux7bra"
assert router._cid_for_bytes(b"") == raw
assert router._agent_dag_json_content_identity({"a": 1}) == dag
assert importlib.util.find_spec("multiformats") is None
loaded = [
    module for module_name, module in sys.modules.items()
    if module_name == "ipfs_accelerate_py"
    or module_name.startswith("ipfs_accelerate_py.")
]
for module in loaded:
    origin = getattr(module, "__file__", None)
    if origin is not None:
        assert origin.startswith(archive + "/"), origin
print(json.dumps({"raw": raw, "dag": dag, "targets": targets}, sort_keys=True))
"""


def test_real_isolated_sealed_capsule_imports_control_plane_and_mints_cids(
    tmp_path: Path,
) -> None:
    pin = _full_source_capsule(tmp_path / "accepted")
    sealed = llm_router.seal_agent_implementation_control_plane_capsule(pin)
    hostile = tmp_path / "hostile"
    hostile_package = hostile / "ipfs_accelerate_py"
    hostile_package.mkdir(parents=True)
    marker = tmp_path / "hostile-imported"
    hostile_package.joinpath("__init__.py").write_text(
        f"from pathlib import Path\nPath({str(marker)!r}).write_text('package')\n"
    )
    hostile.joinpath("sitecustomize.py").write_text(
        f"from pathlib import Path\nPath({str(marker)!r}).write_text('site')\n"
    )
    environment = dict(os.environ)
    environment.update(
        {
            "PYTHONPATH": str(hostile),
            "PYTHONUSERBASE": str(hostile),
        }
    )
    completed = subprocess.run(
        [
            sys.executable,
            "-I",
            "-c",
            _HERMETIC_IMPORT_BOOTSTRAP,
            sealed.executable_path,
        ],
        cwd=hostile,
        env=environment,
        pass_fds=(sealed.descriptor,),
        text=True,
        capture_output=True,
        timeout=60,
        check=False,
    )
    try:
        assert completed.returncode == 0, completed.stderr
        result = json.loads(completed.stdout)
        assert result["raw"] == KNOWN_EMPTY_RAW_CID
        assert result["dag"] == KNOWN_A_1_DAG_JSON_CID
        assert len(result["targets"]) == 3
        assert not marker.exists()
    finally:
        os.close(sealed.descriptor)
